### ISSUE TITLE
Hive BP September Update

### ISSUE THREAD

**Issue by hiveben** [wax-office-of-inspector-general/waxguilds#100]
Hey guys,

Hyperion is working, in fact, we've set up a third node this month, after we unexpectedly hit a limit shortly after setting up the second node, causing us to fall behind for half a day. But that was quickly fixed, so we didn't fall behind the average that grants points.
We also updated our second node to run the same version, getting rid of the status warning. Status warning doesn't mean that the node wasn't running though, it just means ES nodes have different versions. Not sure why stats.eosusa isn't able to track us prior to the 14th, but it was in fact online and we're monitoring it closely.
Running 3 Servers for Hyperion is quite expensive, so the points for that would be nice.

Other guilds used to get up to 3 points for "helping smaller collections" for months. We're doing many things, promotions, retweets, trade feeds, holder snapshots etc. Would be nice to get at least 1 point for all the stuff we're working on.

I strongly suggest that IPFS is considered an API. It helps immortalize WAX NFTs. The more nodes there are for WAX NFTs, the better it spreads through the IFPS network. We can't just rely on cloudflare ipfs and pink. I honestly think it's quite a pity that more guilds aren't offering IPFS services.

Work on product 3 has begun. We're already renting servers for the analytics API and are separating analytics logic from NFTHive. Maybe it can be granted in development points as well?

**Comment by blocksbarcelona** [comment]
Hyperion points have been granted. Regarding smaller collections, please provide detailed metrics. We will discuss internally about the IPFs. Next month please provide detailed information regarding the new product in development so we can evaluate it.
