### ISSUE TITLE
NiFTyLIFE Appeal - September 2021

### ISSUE THREAD

**Issue by Roy-NiftyLife** [wax-office-of-inspector-general/waxguilds#101]
# Product Development Appeal.

## Submission

In accordance with the below sub-sections titled "Pack Breaks as Product" and "Escrow Service as Product" it is submitted for the OIG's consideration that our NFT Pack Breaks and our Escrow service are to be considered separate from each other and to be considered as products for the purposes of Guild ratings by virtue of their unique combination of multiple tools, multiple currencies, cross standard support, separate UI, and smart contract solutions. 

### Pack Breaks as Product

Thank you for recognizing Waxstash market. However, I must ask you to seriously reconsider Pack Breaks, which is also a fully fledged separate product that has been released for one year now. Pack Breaks requires more work than a market in many ways and is supported by over 30 smart contracts (at least one for each pack supported), I am currently building another contract right now for maiden.funko pack break support. Other community products which have been awarded product points require far less development work. Pack Breaks as a product should also be deemed to consist of not just smart contract development but also UI design & development, sorting, filtering, & bundling of wallet inventories, as well as community management & marketing, since these are separate and additional to the market. I understand the OIG's temptation to lump pack Breaks together with Escrow and consider them "community tools", but at the same time this fails to recognize clear differences between tools that have been in the past and are currently considered "community tools", and Pack Breaks. Each Pack supported in Pack Breaks is a "community tool" by itself and therefore should count for 31 (soon to be 32) "community tools", but Pack Breaks goes further and combines them into a product. For example, compare what's required for a telegram bot (an example community tool provided by OIG guidelines) to what I have outlined above and it is evident that Pack Breaks is not only a standalone product, but it is on level with a standalone marketplace. In addition, NFT Pack Breaks remain exclusive to NiftyLife which should stand as a testament to the work required to build and support this product. Please review my original submission further to read more about Pack Breaks and how they create a completely different way for users to buy & sell packs, and take part in the WAX ecosystem.

### Escrow Service as Product

Escrow service was used this past evening to facilitate a private GPK OS1 sale for over 50,000 WAX. Escrow supports private sales for simpleassets & atomicassets, and can be made in WAX, TLM, DUST, or USDT. Each feature included within a tool, like with Pack Breaks above, are akin to being standalone community tools. Escrow is easier to maintain than a marketplace or Pack Breaks, however, still involves quite a bit of testing to ensure cross standard and multiple currency support, UI design, and community management, and to pack all that into a single smart contract. In any event, the Escrow service represents another separate design and development effort that supersedes that of a "community tool" and which should not simply be lumped together with Pack Breaks nor considered a simple tool.

# Tech-Ops Appeal

## Submission

In accordance with the OIG Tech-Ops guideline for "Publishing feed data via an oracle service (e.g. Delphi)" we request either recognition or further explanation of what is meant by this guideline. We currently pull WAX price feed data from the delphioracle contract every 30 seconds, perform computations to average the data, and publish it in a red/green ticker like UI on our marketplace. In addition, with this data we perform computations under the hood for supporting Atomic USD/WAX sales, which require ever changing delphi medians in order to accurately compute the required WAX in a USD pinned listing. We believe that "Publishing feed data via an oracle service (e.g. Delphi)" means displaying the WAX quote to the public, and if so, then we have met that criteria. If not then this must mean something else, such as sending price data to an oracle contract, please advise. In any event, publishing feed data to an oracle contract or from an oracle contract should be considered one in the same. Thank you.

# WAX Strategic Contribution Appeal

## Submission

It is submitted for the OIG's consideration that the unique contributions of NiftyLife in the Markets and NFT Solutions categories rise to some level of WAX strategic contributions. Please see the below sub-sections "Markets" & "NFT Solutions". Noting that WAX Strategic guidelines provide for a point rating between 1-10 for Markets or NFT Solutions that are above and beyond the usual features for those categories.

# Markets

Waxstash is four markets in one. Features and tools that are exclusive to NiftyLife, such as multiple currencies, lend support to other WAX projects and Guilds, and continue to bring outstanding value to the WAX ecosystem. Supporting NFT listings in WAX, TLM, DUST, and USDT creates multiple marketplaces in one, allowing WAX Projects, Guilds, and NFT users to participate in the WAX ecosystem in a way above what a bare marketplace might provide. Providing this should be considered in the range of a valuable contribution to WAX. Particularly in regards to the exclusivity of these features.

# NFT Solutions

NFT Pack Breaks are an outstanding contribution to WAX. It was shocking to se Pack Breaks lumped in with Escrow as a "community tool", when they are their own product, exclusive to us, and contribute to every WAX project we support. Pack Breaks allow users to competitively list their packs into slots, slots prices are chosen by pack owners and can be undercut. For example, if a pack is listed for 50 WAX per slot and there are 5 slots sold, if another user comes in to list their pack for 45 WAX per slot, the higher priced pack is automatically returned, the slots owners are each refunded 5 WAX, and the new pack takes over, absorbing the current slots. This all happens automatically and creates an exciting and unique way for users to participate in strategically selling packs and buying slots. Supported by over 30 contracts each with their own RAM and CPU management. When a popular pack drops this feature contributes to the buzz and pack openings during the weeks following the drop. Thus we believe Pack Breaks should be recognized as a strategic WAX Contribution.

## OIG Suggestion

Within my initial rating it is obvious that the preference (intentional or unintentional) for rating products/tools/contributions is for them to be located somewhere in a separate UI, website, blog etc. I'd like to suggest that this is part of the reason why WAX tools are scattered all over the place. The incentive is to build tools, but there is less incentive, maybe even a huge penalty, to build tools on top of each other for fear they will be lumped together and won't garner any "points". Perfect example is having a marketplace, pack breaks, and escrow (each containing several tools) all built into the same website. It's a huge penalty to have Pack Breaks be considered a "tool" and lumped in with another tool at that. That exemplifies my point. Therefore, in my opinion WAX tools lose value when they become scattered about, difficult to find, use, under different UI's. My suggestion is for the OIG to establish procedures/guidelines/points to incentive products, tools, & features to be built/added together, but rated separately where applicable. This would also have the added benefit of keeping tools updated and maintained over time as there will be an incentive to do so. As new tools are built alongside older tools the older tools might have to be maintained/updated as well, otherwise they could face making new tools appear old. Again, just a suggestion. For anyone who made it this far, thank you.

**Comment by blocksbarcelona** [comment]
All submitted products are part of the market because they cant function independently. We can break it in 3 product if you want, but the total score would essentially be the same. In any case, we need detailed metrics in order to properly evaluate them. if you decide to make the packs opener and escrow Open Source or make them available for other markets to integrate with, we might consider to review them as independent products. Regarding the oracle: the price has to be published on chain using the delphi contract, please ask about it on the WAX BP channels on telegram. WAX strategic points can't be appealed not requested by Guilds. We appreciate appeals short and to the point.
