### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by Avm07** [wax-office-of-inspector-general/waxguilds#1010]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Oracle Data Feed - As s BP performance is measured by test net, should not oracle data feed be measured by test net too.
We do on test net with >95% uptime but don't have enough resources staked on the main net to provide >95%. Can we get some stake on main net for this purpose?

BP: bp.adex

Thank you

**Comment by rakeden** [comment]
Hello A-Dex guild!

we have verified the "price oracle" contribution on testnet and by reviewing pairs and uptime, come to the conclusion to award your guild the missing points as well as removing the penalty for a missing price oracle.

kind regards,
the WAX OIG
