### ISSUE TITLE
Appeal - BlokCrafters September 2021 

### ISSUE THREAD

**Issue by nickeles7** [wax-office-of-inspector-general/waxguilds#102]
We would like to appeal our category's Ecosystem Development & Community Engagement (creation of original information)

Ecosystem development - We would like you to reconsider the 0 points you awarded us for nftorigions.io. please take a look at submission again, as we already have our first partnered collection tangiblenfts.io we built and are closing in on our second partnered collection. 

Community Engagement (creation of original info): We would like you to reconsider the 2 points you awarded us. We have been consistent in this category for several months now with interviews/livestreams, tool overviews & project highlights. please take a look at our submission again  and or have a look at our YouTube channel. https://www.youtube.com/c/BlokCrafters/videos 

Thank you!

**Comment by kaefergeneral** [comment]
nftorigins has been awarded 0 points as of now there have not been any releases.
It does not provide any self-service tools or instructions other than a linked google doc to request a partnership.
So it will credit points in line with how all other guilds are scored based on the launch performance of supported collections.

As for community engagement, the score received already includes a bonus for consistency. The content right now is lacking distribution and impact.
