### ISSUE TITLE
Ledgerwise Appeal - Sept 2021

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#103]
Notion report for September is not reflecting the current score but for the last month. 
We shared and promoted the Community update on Twitter and Discord. Please check here https://twitter.com/ledgerwiseio/status/1440279327539486728?s=1

**Comment by rakeden** [comment]
Hi Tanish, 

the score has been corrected. You have been granted the extra points for the blog post.
