### ISSUE TITLE
WAX Eastern Appeal- Sept 2021

### ISSUE THREAD

**Issue by waxeastern** [wax-office-of-inspector-general/waxguilds#104]
Dear OIGs,

We would like you to reconsider the 0 point for the Oracle Service we provided, it's been up running well. 
![](https://i.imgur.com/QISWy5V.jpg)

Also, we've been actively coordiating with ZB Exchange （the top 5 crypto exchange in China）to list WAXP and TLM tokens. Wondering if that could be taken consider into the ecosystem score as well.

And for the WAX Strategic Contribution-Marketing and Promotion part: we've helped WAX and Alien Worlds team to attend 3 NFT Related Events and AMAs (Odaily N-Power Carnival, Metaverse AMA held by HyperPay and NFT Related AMAs by ZB) to promote the WAX Ecosystem, we are wondering if you could reconsider on that.

Thank you OIGs.

**Comment by kaefergeneral** [comment]
Your Oracle Service is 'up and running' but it does not seem to actually update the prices. It's regularly stuck on the same price for hours while there actually have been price swings of multiple percent across other exchanges.
So the datapoints you are aggregating don't seem sufficient.

We had some issues with verifying ZB during our review as their site would not load and coinmarketcap does not list any WAX pairs on ZB. We now added points for it.

We will never grant strategic points on request.
You received a full score of 3 points for your efforts in "Marketing and Events" at this stage we can not see any 'extraordinary' efforts or impacts on the WAX ecosystem that would warrant extra points beyond the already top score you received.
