### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#1046]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Atomic API - running with average of around 97% - awarded zero points. 
2. IPFS Resizer - we added videos for IPFS resizer this time, would love to get atleast 2 points. 
3. Total mistake - Seems total comes out to be 215, but showing 209. 

Thank you

**Comment by rakeden** [comment]
Hello Guild,

we revisited the evaluation and came to the following conclusion:

1. Atomic API --> ~80% SLR for v5.8T3 (07/01-07/14), which results in 0 points for AA API
2. IPFS Resizer --> The score for this contribution has been increased to 2 points
3. Total mistake --> Thank you. The total score has been corrected

Best wishes, 
OIG
