### ISSUE TITLE
RATING APPEAL - EOSDACSERVER JULY 2024

### ISSUE THREAD

**Issue by paplooo** [wax-office-of-inspector-general/waxguilds#1047]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Galactic Hub - Galactic hub has funded a plethora of projects which can be found in our OIG submissions, however we have not been receiving the points for new releases. The last edit on this was on March 10 in the contributions section of the OIG notion site. Below are the new projects funded and released through Galactic hubs grants program

- Unity SDK for Mobile
-  Lynx AI
-  Starblind Zero "Comic for Alien Worlds"

Request to OIGs to consider Galatic Hub as platform instead of just a product, look out for the new releases through Galactic Hubs and rate accordingly

Thank you

**Comment by kaefergeneral** [comment]
Hello eosdac,

we migrated the Galactic Hub to an ecosystem development. This was initially not done as products scored higher.
We also increased the score to 3 for the time being. 

Best Regards,
your OIG
