### ISSUE TITLE
QARQOL JULY 2024 RATING APPEAL

### ISSUE THREAD

**Issue by qaraqol** [wax-office-of-inspector-general/waxguilds#1049]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Backups- Can you please explain why we receive no recognition for us providing backups for chain db, atomic assets, etc at https://snapshots.qaraqol.com/ 
3. WAX IPFS Script- Can you please explain why we receive no points/continued decay for our ipfs script even though we made a major update as documented in our update (https://github.com/wax-office-of-inspector-general/waxguilds/pull/1037/commits/0bdec81e59c1e19ddaf9080f468fd47fd7ae267c)

Thank you
we are unsure if this is related to making a basic mistake with submitting the report but hoping it can be fixed

**Comment by kaefergeneral** [comment]
Hello @qaraqol,
1.  We added the scores for your backups based on your submission reporting Atomic Assets and Chain-DB.
2. We removed the decay as it was not intended to be applied in this evaluation. Thank you for the heads-up.

Best,
your OIG

**Comment by qaraqol** [comment]
Thank you @kaefergeneral 

We see the strategist was changed to 1 point with a decay target. Is this a mistake or what does this mean?

**Comment by kaefergeneral** [comment]
Thank you. The change was unintentional. 
What was supposed to be updated was the Score of the IPFS script.
This has now been fixed.
