### ISSUE TITLE
3DK Render Appeal september 2021

### ISSUE THREAD

**Issue by 3dkrender** [wax-office-of-inspector-general/waxguilds#105]
Dear OIG:

We believe there may be an error in the validation of the monthly CPU latency. We have not exceeded the range of 0.35 ms at any time. We would like to request a review of this section. Thank you.

![image](https://user-images.githubusercontent.com/51716993/135267272-3c72d775-89d6-4947-8145-fb7843557609.png)

**Comment by kaefergeneral** [comment]
Typo corrected. A score of one is not possible in that criteria. Thanks for the highlight,
