### ISSUE TITLE
RATING APPEAL- WAX Eastern

### ISSUE THREAD

**Issue by waxeastern** [wax-office-of-inspector-general/waxguilds#1050]
Good Day IG's,

Can you please have a look at the points we have awarded for the following:

**Collaboration with WAXDAO**: We partnered with WAXDAO to translate their UNITY game tutorials. These translations are highly professional, covering an extensive series of 9 tutorials. **This is an entire series of translations, not just a single piece of content,** this should also qualify as a separate ecosystem engagement.

**WAX ACADEMY Course**: In collaboration with WAX SWEDEN, we completed the remaining half of the WAX ACADEMY course translations. I don't understand why there is still decay despite the courses being fully updated.

**Comprehensive WAX Content Platform**: We have developed a comprehensive content platform about WAX, which includes summarized and original introductions, project tutorials, and translated materials. It serves as a one-stop solution for Chinese-speaking players. Could you please clarify why this did not receive any recognition?

We would greatly appreciate your guidance on these matters.

Thank you,
Monica

**Comment by kaefergeneral** [comment]
Will be revisited with Evaluation 5.10.
