### ISSUE TITLE
RATING APPEAL - A-DEX BP

### ISSUE THREAD

**Issue by Avm07** [wax-office-of-inspector-general/waxguilds#1051]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

Products:
1. A-DEX Swap(https://wax.a-dex.io/swap) - too low points, dedicated dApp written from scratch, involving multiple engineers for smart contract, frontend, backend, and covered audit and developing cost definitely should receive more points(±40-60) as existing Defi dApps. It should not receive bare minimal points as simple scripts with 100 lines of code.
2. A-DEX Analytics(https://wax.a-dex.io/analytics) - missing product, DEX analytics with core metrics(TVL, Volume, UAW, Transaction, Fees, APY, Actions). All data is available from our GraphQL API.
3. A-DEX Send(https://wax.a-dex.io/swap) - missing product, web wallet for managing your tokens, sending tokens anywhere(CEX, DEX, dApps).
4. A-DEX Buy(https://wax.a-dex.io/swap) - missing product, fiat & crypto users on-ramp direct to WAX.
5. A-DEX SDK(https://github.com/A-DEX/a-dex-sdk) - missing product, open-sourced Typescript SDK for building products on top of A-DEX.

Community Tools:
1. Assets (https://github.com/A-DEX/assets) - missing community tool, a comprehensive, open-sourced, up-to-date information collection about Antelope(EOSIO) chains. Including chains, tokens, wallets logos, and info.

Infrastructure:
1. AA API(https://wax.a-dex.xyz/docs/) - missing points for publicly available service
2. IPFS(https://wax.a-dex.xyz/ipfs) - missing points for publicly available service
3. Hyperion Testnet(https://hyperion-wax-testnet.a-dex.xyz) - missing points for publicly available service
4. Hyperion Mainnet(https://hyperion-wax.a-dex.xyz) - missing points for publicly available service

Thank you

**Comment by kaefergeneral** [comment]
Hello @Avm07,

Product:
We base our evaluations on value contributions. 
This, in return, means we evaluate contributions like exchanges based on user metrics.
Unless the metrics require us to split a product into separate parts, they will be bundled, like in your case, A-Dex and related tools.

Community tools:
The repository provided does neither include a comprehensive nor up-to-date asset list for WAX. Even if it were, we would still require people to use it before we consider granting points. 

Infrastructure:
1. Points for Atomic Assets were granted with the v5.8T4 evaluation, as you did not qualify for points prior.
2. Points for IPFS have been added
3. Hyperion Testnet - Your endpoint was added on July 17th and is wrongly flagged as full. It does not qualify for points.
4. Hyperion Mainnet was only added to your BP.json on July 26th. Therefore, it does not qualify for a score in the infrastructure evaluation covering July 15th through July 28th.

**Comment by Avm07** [comment]
> 3. Hyperion Testnet - Your endpoint was added on July 17th and is wrongly flagged as full. It does not qualify for points.

It launched from ES snapshot and contains full indexes with 0 missing blocks. The ship node saves the latest 1 month of history but covers the latest indexed block of ES.
