### ISSUE TITLE
RATING APPEAL - EOSphere Guild

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#1052]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Commercial API Services - We appear to have been degraded to 0 points for our commercial services offering.

Thank you

**Comment by kaefergeneral** [comment]
Thank you.
We are decaying the scores for all commercial API services, but it was only supposed to be noted, not applied.
This has been fixed.
