### ISSUE TITLE
Qaraqol RATING APPEAL September

### ISSUE THREAD

**Issue by qaraqol** [wax-office-of-inspector-general/waxguilds#1089]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Strategist- We made a major update to the strategist this evaluation period, updating the backend to allow for users to determine the nft point conversion rate instead of a hardcoded rate, new filters/sliders for users to tune their builds more, and tooltips so its easier for people new to WAX and Alien Worlds to understand. We understand we don't have much growth when it comes to users because we were only able to release the update a few days before the submission deadline. We ask for a little more time.

Thank you!

**Comment by blocksbarcelona** [comment]
Hi Qaraqol team,

Thank you for reaching out. After some internal debate and reviewing your proposal and appeal again, we have decided to restore the 0.5 points previously assigned to your product. We encourage your team to develop new, original projects that are not based on existing products developed by another guild. 

We look forward to seeing what you will bring to WAX.

Regards,
