### ISSUE TITLE
DLT Rating Appeal

### ISSUE THREAD

**Issue by robrigo** [wax-office-of-inspector-general/waxguilds#1091]
Good Day IGs,

Can you please have a look at the points we have awarded for the following:

1.  We've been running a full Hyperion on WAX and received a 0. While we understand there was an outage, it would be cool if known providers would at least get some acknowledgement for running full which is harder to keep maintained. We easily spend 4 figures on our full infra on a monthly basis.

2. FACINGS has 2 products, the Collection Manager and the Studio. Currently they are combined and we only receive 1 point. Can you acknowledge that FACINGS has 2 separate products please?

3. We've been conducting an open beta for the upcoming Pantheon game which is nearing release in coordination with the WAX ambassadors. We've requested development points to acknowledge this, however we got a 0. Can you please explain? This is a game that we built based off a referral from the WAX core team and it reinforces the core narrative of NFTs + gaming on WAX so we're confused why this doesn't get any consideration at all when we've invested a ton of time and energy preparing this.

Thanks,

Rob

**Comment by kaefergeneral** [comment]
Hello Rob,

1.) Unfortunately, we have to evaluate all guilds by the same standards and can not bend the rules in individual cases. Infrastructure is assessed on a 14-day basis. For the given timeframe of 26th of August through 9th of September, your Hyperion endpoint was reported down across all three validators we commonly use for a minimum of 11 days, with the highest healthy uptime reported by Validationcore at 11%. Even now your Hyperion health check is in an erroneous state so we would recommend to check on that.

2.) Listing products in separate rows does not impact the rating or define the acknowledgment of listed products. Having multiple products bundled in one row can occasionally work in your favor, but if you prefer to have them separated, we can do that.

3.) Points granted for products 'in development' follow stringent guidelines. There seems to be a disconnect here. Neither did you report an open beta with your latest submission, nor did you request points in development for it. Given the potential severity of failing to deliver after points in development were granted, this only happens upon specific request and with a predefined agreement and schedule between guild and OIG. When you asked about how to apply for points in development, we let you know that we would like to wait out the beta in August so you can show us some gameplay and provide us with a marketing and release schedule. You were also informed that you would usually have to schedule a discovery call specific to Pantheon with us, and we would then work out the details of potential points granted. Given that you did not provide us with Gameplay, invite us to partake in the closed beta, work out an agreement with us, or officially request points in development, we assumed you would be aware that points would not just be granted and that it was a conscious decision on your end as it seems the release now is closing in anyway. If you do not hold the Pantheon sale before the next evaluation cut-off and want to apply for points in Development, please schedule a call with us.

Best wishes,
your OIG

**Comment by robrigo** [comment]
Hey Kaefer, thanks for the feedback. My responses to your answers are below.

1) I am not asking for special privileges, I'm suggesting that the framework may want to acknowledge the risks guilds are taking by running full infrastructure even if they have an outage. That's why I specifically said "known providers" to include anyone else that may be in a similar situation.

2) I don't really understand why it would make a difference if they were bundled or not since we aren't getting points for 5 products yet, wouldn't it just be that the products are worth the same points regardless of if they are included on 1 line or 2? The way you're doing it makes it harder for me to understand what the Creator is worth vs. the Studio.

3) If you read the OIG report again, you'd see that we said "Pantheon, our TCG, had its closed beta period during this reporting period. We cordially invite the IGs to play test the game with us as time permits."

And also 
* "Closed" beta was performed over the August 11th to August 31st timeframe on the WAX testnet. The game is in a stable state with various bug fixes and quality of life features planned to be implemented during the month of September. The beta had multiple game tables running at one time and 20-30 people participated.
* The mainnet pack sale will take place during the first half of October, and the live release of the game will take place in the second half of October.


So I find it curious that you claim we said there was no beta and we didn't invite you guys to participate.

See here: https://github.com/wax-office-of-inspector-general/waxguilds/pull/1082/files

**Comment by kaefergeneral** [comment]
Hi @robrigo,

1.) Currently, the great majority of Hyperion endpoints provided are full history endpoints. In contrast, the vast majority of requests only require partial history. Given the huge discrepancy in cost, providing full history compared to partial history, we actually want to discourage guilds from running full history in favor of cheaper and more reliable partial history endpoints. In the mid to long term, the current system of how history endpoints are evaluated will change, with the likely outcome being that full history will not receive any points over partial history when it comes to evaluations. Full history endpoints will instead be provided by dedicated providers, e.g. selected reliable guilds, and paid separately, outside of guild rewards. 

2.) The difference is that if products are bundled, we also tend to bundle the metrics. This, in return, can result in the favorable application of decay, where an update or good metrics of one can keep the total score up. Separated, the score of one might not be enough to lift the score, and at the same time, the second product might decay. This results from applying 0.5pt steps in the scoring progress and how we internally agree on scores being three IGs. If we end up with one project with 0.66 points and one with 0.166, you end up with one project getting 0.5pts and the other 0. Bundled, the consensus would grant 0.833 points, resulting in 1 point being attributed.

3.) Correct, you reported a closed beta for Pantheon running from 11th through 31st of August. Given that the report, and with it an invitation to test the game, was submitted on the evening of the 31st, the beta had already ended when we became aware of it. We did not say you did not mention the beta, we specifically said you did not report an open beta, and did not invite us to the closed beta.
You invited us to playtest the game with you 'as time permits', which we are happy to do and look forward to.
From our understanding, a closed beta is invite-only. You are either invited, or you apply for it to receive an invite.
Given that we did not see the news of the beta shared anywhere, we could not know it was taking place, and as such, we couldn't reach out about it. 

Please note, that while the responses are posted by one individual, they are written and agreed upon by the entire OIG. Not an individual IG.
