### ISSUE TITLE
RATING APPEAL - Ledgerwise

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#1128]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. IPFS and Light API - We have started providing light APIs and didn't get points for it. 

Thank you

**Comment by kaefergeneral** [comment]
Hello @Tanishv,
Thanks for the heads-up.
Scores for light-api will be added with the infrastructure evaluation next week, as we are currently only evaluating product and ecosystem contributions.

Kind regards,
your OIG
