### ISSUE TITLE
A-DEX BP - RATING APPEAL

### ISSUE THREAD

**Issue by Avm07** [wax-office-of-inspector-general/waxguilds#1137]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Atomic Assets Snapshots - New dump was generated on 13 November

Thank you

**Comment by kaefergeneral** [comment]
Hi @Avm07,
After some discussion, we decided to remove the retention criteria for AA with the next guideline version and grant you the points this time. In the future, please ensure your provided backups are current and the required retention periods are upheld.

Thanks
