### ISSUE TITLE
EOSphere - October 2021 appeal

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#138]
Good-Day OIG

We have two appeals:

**Fulfilling monthly requirements**
Publishing our Guild Monthly Update and promoting wasn't counted.
https://medium.com/eosphere/eosphere-guild-october-21-update-9207a7fdd0ed
https://twitter.com/eosphere_io/status/1449545006373429253?s=20

Also are there any points from providing our rate limit information, which we did?

**Technical Minimum and Secondary Requirements** 
Of course we understand that there was an outage and we dropped 16 rounds giving us a round availability of  99.92% . However the v3.3 OIG Guidelines say that the Minimum threshold is 99% and Secondary Threshold is 99.5% .. both of which were achieved. The OIG score card then differently advises 99.95% for the Secondary Threshold which we didn't achieve and hence weren't rewarded the points.

Appreciate you looking into this.

**Comment by rakeden** [comment]
Good Day Ross,

we revisited your evaluation and made the following changes:

**Fulfilling monthly requirements**
- we granted an additional point for the monthly update post.

Technical Minimum and Secondary Requirements
- Unfortunately we can't grant more points. Thanks for the feedback on the thresholds - We are revisiting the criteria in the following month and will update the wordings accordingly.

**Other changes** 
- We added an additional .5 points for your community management initiatives. Keep up the good support!
