### ISSUE TITLE
NiFTyLIFE - October 2021 Appeal

### ISSUE THREAD

**Issue by Roy-NiftyLife** [wax-office-of-inspector-general/waxguilds#140]
## Building and supporting community tools

Thank you for recognizing Pack Breaks as a product, we have more planned for Pack Breaks coming this month. However, our Escrow service remains live and supported as a community tool, which I believe was overlooked here.
Thank you for recognizing Pack Breaks as a product, we have more planned for Pack Breaks coming this month. However, our Escrow service remains live and supported as a community tool separate from Pack Breaks and separate from Waxstash (although under the Waxstash url), which I believe was overlooked here.

Thank you.

**Comment by rakeden** [comment]
Thanks for the feedback.

We don't aggree that the Escrow service should be rated separately from waxstash and therefore left the points as they are now.
We did however revisit your evaluation and noticed that we didn't grant you points for the monthly update post - We added a point for this.

keep up the good work.
