### ISSUE TITLE
Blacklusion - October 2021 appeal

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#141]
Here is our appeal for October 2021:

As the months before we were also publishing feed data via the Delphi oracle. However, we got scored a 0 for that this month. 

I read in another appeal that they did not get any points for the additional monthly report as well. So I am not sure if there were some changes to that category. Basically, we also published a secondary report and shared it on social media, but did not get any points on that.
https://twitter.com/blacklusion/status/1451288614780948488?s=20

Thank you for looking into this!

**Comment by rakeden** [comment]
We've looked into your oracle data and granted the points. Our monitoring failed to track that stat correctly, so thanks for pointing that out.

We also granted an additional point for your monthly published post.

Thanks for the feedback and congrats to reaching standby.
Keep up the good work and improvements.
