### ISSUE TITLE
BlokCrafters - October 2021 Appeal

### ISSUE THREAD

**Issue by blokcrafter-dan** [wax-office-of-inspector-general/waxguilds#142]
### October 2021 Appeal
Hello Inspector Generals, we would like to submit an appeal for our scoring this month in the following categories.

#### Technical Operations
We are questioning the scores for the following item in TechOps:
- Providing useful APIs. (e.g. Simple Assets, Atomic Assets) (0 to 2).
Only 3 guilds received the score of 2 for this.  We’re not sure what qualifies to receive a score of 2 - is it a simple matter of providing more than 1 useful API?
We provide the Atomic Assets API and have kept it running and current with the blockchain for the entire month.  Many guilds (16) have also received a score of 1 for this, presumably also for serving the Atomic Assets API; but the problem here is that a number of these guilds have not kept the AA-API running and up to date.  We do feel we should have received a score of 2 in this category for the quality of service we provide for the AA-API.  
**Please clarify the scoring for this - what exactly qualifies at a minimum service to receive a score of 1.  What exactly qualifies at a minimum to receive a score of 2.**

**Comment by rakeden** [comment]
Thanks for the feedback. We've looked into your case and want to clarify your remarks.

We grant a point for each useful API hosted and provided. e.g. AtomicAssets, SimpleAssets (not anymore) or other usable APIs, like nfthive is releasing an API for market sales data.

High-Usage APIs could lead to an additional point if a high load can be proven. Also the development of a useful API can grant additional points, if proven to be used in production.

**Comment by blokcrafter-dan** [comment]
Can you be more specific on what counts as a high load for the API?
We will include data next evaluation regarding this.
The past 30 days our servers have handled > 630 million requests.

**Comment by rakeden** [comment]
Thank you for providing the usage data in the upcoming month.
We will revisit the criteria for APIs once again in the following month and clarify the criteria to include API hosting, API Usage, and API development.
