### ISSUE TITLE
Token Gamer - November 2021 Appeal

### ISSUE THREAD

**Issue by beasteh** [wax-office-of-inspector-general/waxguilds#174]
Hi OIG,

We believe that our IPFS endpoint may have been overlooked during the evaluation. We believe that this falls within the "Providing useful APIs" category and kindly ask for this to be double checked. 

Example
https://ipfs.tokengamer.io/ipfs/QmeSXAbzuDQDkwBhspzyj9Ltz5m58UcBypCLvjcDRg4eAT/Base/25-KOLIN-Base.png

Thank you!

**Comment by kaefergeneral** [comment]
Points for IPFS have been credited.
