### ISSUE TITLE
Dapplica Appeal

### ISSUE THREAD

**Issue by dapplicaio** [wax-office-of-inspector-general/waxguilds#175]
1. Please let us know why we received no points on "99.95% to 100% Round  Availability uptime on block signing node for the guild's last full month of WAX mainnet data, or testnet data if mainnet is not available. (0 to 2)" ,   Dapplica had no missing rounds from June https://t.me/WAX_Mainnet_Aloha_Tracker 
2.  Fullfilling monthly requirements (0 to 3). Seeing no points on this one too, but I remember we had last month as an article on Guild Update was published at Dapplica.io blog and reported into Guild report. 

3. On business development: 
- Wombat is already on WAX and as reported it got over 50k of accounts created via wombat at a time of report, I assume it has to have status Onboarded on WAX. And project brings big value, as it has 1M of users(eos, eth) so many of those will be activated into WAX.

- DeepMine also on WAX(status Onboarded on WAX), we put in previous report also about the project, it's successful sale.  Dapplica is tech partner for DeepMine and Oleh is product advisor, please find that information at [deep](https://deepmine.world/) , Dapplica is developing smart contracts and part of frontend code for deep mine game( stacking contract is at testnet already "deepminegame" and to be deployed on mainnet in next day or two). 

- May we know why Prospectors is removed from our BD sheet? Also we onboarded another project https://darkgalaxies.io/ and advising them. (we reported it in previous reports too, but now decided to put Wombat on top), but if there are reasons that Prospectors is removed not by mistake, then please consider Dark Galaxies. It's on WAX already, had an NFT sale and released Alpha version of game last month.

**Comment by blocksbarcelona** [comment]
Hi, our answers below:

1) Fixed. we have added the points
2) we are not granting points for the post anymore. But we encourage Guilds to keep publishing it. Thanks!

- Wombat was decayed long ago and even you asked to switch from wombat to dark galaxies in June 2021
- Next month please add more detailed information on what you are doing for deepmine. With the limited information you provided we grant 1 points for developing the smart contracts (see new rules for ecosystem development)
- Prospectors was decayed long ago. Ecosystem development tend to decay. Right now WeCan gets full credit for Prospectors as its their product. If you want to claim some points for development you have to contact WeCan and agreed on how to split the points with them.
- Dark Galaxies: we grant 1 point on the basis that next evaluation you will provide a full report on what is your contribution to that project.

**Comment by dapplicaio** [comment]
Thanks, but we never got any points for Wombat, they just entered WAX ecosystem basically last month with lots of Promotions. 
As for deepmine, is there any formal way to provide more information then, what are the conditions. Cause we are only dev team that does WAX related job for them(smart contracts and frontend integrations), how we can provide more info on that? Also Oleh do consult them on pros and cons of different approaches regarding game functionality in the future and with current staking in particular. 
As for Prospectors , we raised that question sometime ago, and being told that it can be okay if project was brought by one GUILD and developing by another.

**Comment by blocksbarcelona** [comment]
You have to provide as much information as possible for every project. Including detailed scope of what you are doing for that project, milestones, etc.

regarding prospectors its of if one guild develops for another one. Nothing wrong with that. But unless both guilds own the IP, the owner of the game should agree on sharing the points with the other guild. Its their call.
