### ISSUE TITLE
November 2021 Appeal

### ISSUE THREAD

**Issue by hiveben** [wax-office-of-inspector-general/waxguilds#176]
Hey, just a quick request. Please check whether our points for community tools can be increased to 2, since we are now also running a Twitter sales feed for highlight sales. It was necessary to fight Twitter TOS, adjust the content of the Tweets, the frequency, create a second account in order to get it approved after the first one got banned and it still gets a lot of new followers and engagement every day. All sales bots on Twitter, Discord and Telegram follow different rules and use different APIs. On top of that, we have an IPFS (if it's not a useful api, maybe it can be a community tool), and the Hive-E Notifications bot, which had some updates as well. It informs you about your NFT sales, new drops of collections that you follow and new listings of assets that you're looking for

**Comment by kaefergeneral** [comment]
Hi Ben,
points for useful APIs have been adjusted to include IPFS. We did have to remove erroneously added points for the WAX Marketcap API under useful APIs. 
You were granted an additional 0.5 points in the community tools category.
