### ISSUE TITLE
WaxGalaxy(greeneosiobp) Appeal

### ISSUE THREAD

**Issue by sukeshtedla** [wax-office-of-inspector-general/waxguilds#177]
Hi,

We are wondering why our Kryptoskatt app is removed from our evaluation? We launched the beta almost 1 week back and we have more than 50 organic signups on the platform and are waiting to ramp up the marketing to our pre-launch waiting list users and to the WAX community.  If you haven't checked out the latest platform, please see the screen recording here:

https://www.loom.com/share/a52582d6236440bcb9a13ac6fb35a1c9

Also, our WAX Standalone API services are already being used and now we are near ready to launch the API as a Service subscription, we are doing final testing and scaling to HA mode, setting up subscription models etc before the launch. It would be great to have more points. Please have a look at the screen recording below:

https://www.loom.com/share/c799f80bb9f14897a75a1ea689d3fd92

Could you please share feedback on the above? We also requested a meeting to present the above over a call but it's postponed and scheduled to be on the 16th.

**Comment by blocksbarcelona** [comment]
hi, thank you for reaching out with your appeal.

We have tested Kriptoskatt again. Two IGs tested it and didnt worked for us. We believe the platform has potential but its not quite there yet. As soon as you have a few hundreds users using it (for the WAX part), we would be happy to grant points to it.

The WAX API services will be rated soon. Thanks for working on it.

**Comment by sukeshtedla** [comment]
Hi, 

Can you elaborate on what do you mean by didn't work for us? From what I can see in the logs on both prod and dev, there were two Signups and two accounts were added and all the data was fetched and everything went smooth from what we can see.

So any issues which we might have missed would be really great to know.

**Comment by kaefergeneral** [comment]
On my end:
It first did not work on brave, so I switched to chrome.
The first wallet I tried to import was never completed. I got a spinning circle for around 10 minutes with the wallet not being added, and as such not synced. The next wallet I tried, with fewer transactions, went through but would not show any NFTs or NFT related transactions. 
I would get errors like these:
![image](https://user-images.githubusercontent.com/10457284/146191248-26c1effb-ab00-4a00-8e33-c7812a088952.png)

My profile kept defaulting back to Sweden and SEK multiple times.

There are no prices for WAX based tokens. 

WAX based tokens and NFTs are the main point of having a WAX tax report.
As neither of these are working we don't see fit to grant points.

**Comment by sukeshtedla** [comment]
Anyways, thanks for the feedback. We will try to improve the platform features and bugs.

**Comment by kaefergeneral** [comment]
I refreshed the site again and now it's showing NFTs for me and the error is gone.
But it's still reporting wrong values. From what I can tell at a first glance it's reporting the current WAX value for assets sold. Not the value from when it was actually sold.
![image](https://user-images.githubusercontent.com/10457284/146193889-622d7795-775e-4dad-bb36-1c0ce7b674f9.png)

**Comment by sukeshtedla** [comment]
This bug has been identified and we fixed it in our dev environment, the new build will be launched soon. 

Thanks for checking again and sharing the feedback, we will improve it by the next evaluation cycle.
