### ISSUE TITLE
 BlokCrafters November Appeal 2021

### ISSUE THREAD

**Issue by bdickey32** [wax-office-of-inspector-general/waxguilds#178]
Hello IG's 

 We would like to Appeal our score in Product Development and Ecosystem Development. 

 Product Development - We would like to appeal our score in this category - we feel it should be scored
 higher than 1.  The information in the Product Sheet for scoring needs to be updated.
MyNifties is officially released - we will continue development work on the product by
 fixing problems and issues, as well as adding new features.

 Information on it can be found at:
 - https://mynifties.io/
 - https://apps.apple.com/us/app/mynifties/id1584284510
 
Ecosystem Development - We would like to appeal our score in this category to higher than 1.
We did fulfill the monthly requirements (score 1) and feel we should also receive points for our work in launching 
TangibleNFTs vIRL NFT collection via NFTOrigins. 

Information can be found at:
- https://tangiblenfts.io/home  
- also collection data at https://waxmarketcap.com/collection/tangiblenfts 
 
Thank you,
The BlokCrafters Team

**Comment by kaefergeneral** [comment]
Dear Blokcrafters guild,

Thanks for your appeal.

We’ve revisited MyNifties App a few times during the evaluation period, and it still shows severe bugs.

Here are some observations:
- Linking wallet does not work properly
- WAX Balance does not show
- App crashes when clicking the profile icon

We will re-evaluate with the next report. Please report improvements you make and features you add until then. For now, it will stay flagged as „underdevelopment, “ and points will remain unchanged. Remember to include usage statistics.

Criteria „Fulfilling monthly requirements“ was not applicable for this evaluation as we did not announce any requirements. We want to encourage guilds to continue publishing their monthly updates on social media; as such, these updates will contribute to the regular content creation score.  The OIG will announce monthly requirements upfront and define actions and points to be earned.

While we like the concept of the TangibleNFTs release, we feel the impact fell short. The website itself and processes are very confusing. There is no trade volume post-launch, and the initial sales volume also fell short. We did add a score under NFTOrigins. We would be happy to credit a higher score if you extend the business and create a bigger reach and impact, as we think the whole process has great potential. Feel free to schedule a call with us to discuss your goals and efforts.

Kind regards,
OIG
