### ISSUE TITLE
EOSUSA November Appeal

### ISSUE THREAD

**Issue by eosusa** [wax-office-of-inspector-general/waxguilds#180]
Looks like I need to provide some additional updates related to our products and services we offer.

Regarding history services, while I have not opened our Hyperion clusters up for full public access at this point, we do offer the Hyperion services privately for some projects that are requiring history data but not needing it to be completely open for public access.  Not sure what exactly counts but we do run and offer Hyperion, its just not wide open for public abuse (offered on non-standard ports/addresses) :)

We've continued developing our AWButler service to have additional logic to integrate some new APIs from AW that help determine if a player should qualify for any community drops of NFTs of tokens from the game (or community events).  It might also be important to note that the AWButler service we run has been the only form of NFT automation for the Alien Worlds game for the past several months since they disabled their internal NFT drop process and relied upon ours.

Additionally, we have continued development on the data reporting system, which we have branched out to include much more information than just the original AW mining game data.  This additional data is being used by many projects now to help them wade through the blockchain data to better run events/promotions.  The reporting system now also collects AtomicMarket information for specified collections to allow the artist to properly track and report their commissions for all historical sales.  We are also in discussions with other projects (for example, ToC) about adding their information into our systems to provide additional automation services for their platform as well as develop APIs for collecting and providing their game data via API. https://reporting.eosusa.io although we haven't focused on the UI dev side yet as you might see :))

Also have been working on several other automation services that several clients are actively using and we are discussing with more projects all the time to provide additional automation or blockchain services where needed.

* Alcor LP Rewards - On a regular schedule (6hrs for this example), the status of the project's LP on Alcor is pulled and an automatic distribution based on % held is distributed automatically to the LP holders (137.5MST split up based on %).  The system has configurations to allow for owner/banned accounts to be excluded as well as a low-end threshold to prevent spamming low balance accounts with tokens (RAM's expensive :)). https://aw.eosusa.io/awbutler/mercarts-liqpool.html

* Collection Scoring - On a regular basis, a snapshot of the projects entire collection (this example has over 1100 templates across 6 different collections), all automatically and fully transparent logging for validity.  Once the collection snapshot has occurred, the system then calculates a score automatically for each template based off the number of cards in the template (so lower quantity assets are scored higher than commons).  Then every account holding even a single collection asset has it's score calculated (what we call their "collection score").  That score is then being used for many further promotion/drop events, such as monthly token distribution (based off your collection score; currently 1:3).  We also use the collection scoring to identify groups of collectors and send rewards (ie: everyone over 2250 gets an entire set, then tiers below get fewer rewards).  
   - Collection Scores:  https://aw.eosusa.io/awbutler/mercartscore.html
   - Score generation log (Warning; huge TXT file :)): https://aw.eosusa.io/awbutler/mercarts-scoringlog.txt
   - Example of complex drops based off collection snapshotting (older but good example of complexity allowed): https://aw.eosusa.io/awbutler/mercarts-septdrop.html

* Other Token Automation - Other projects have reached out to us to assist with processes to automate different blockchain activities, one of which is sending out promised project token's based off holding certain assets.  For instance, for the BitcoinBabes project, they created a BABE token miner but needed a system for automating the distribution.  So we programmed a process that runs every Tuesday to snapshot all holders of the required templates and drop the respective amount of tokens into their account and has logic embedded to skip owner/market/banned accounts as well:  https://aw.eosusa.io/awbutler/bitcoinbabes.html

* WAX Resource Planner - Still operate and maintain the https://waxrp.eosusa.news resource planning site for the chain

* Also forwarded over some private information to the OIG email regarding other development projects we have been working on with our partners/clients but didn't see any reference to them in the review.

As always, attending some of the different podcasts and interviews around the ecosystem discussing the EOSIO platform.  Mostly discussing the state of EOS on this podcast but mention WAX and the bridging of all the EOSIO chains a bit during the call: https://www.youtube.com/watch?v=bkBS_dOk21E  Also did an interview with Bloomberg.com about the Alien Worlds platform and Play2Earn projects on WAX (altho took a while to get published): https://www.bloomberg.com/news/articles/2021-12-07/play-to-earn-crypto-gaming-apps-surpass-defi-in-user-popularity

**Comment by blocksbarcelona** [comment]
Your email was overlooked, thank you for the remineder. The projects have been added to Ecosystem Development.
