### ISSUE TITLE
blacklusion November appeal

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#181]
Hey IGs,

here is our appeal for this month. I hope I am getting the notion tables correctly with the adapted evaluation schedule. I will be referring to the December table, since it matches the score in the current guild ratings table, even though this appeal is about the November submission:
1. We shared our guild update on medium and social media prior to the guild cutoff. I am not sure if this was just overlooked or if this has to do with the new evaluation schedule, but the notion table states that it is not applicable for December. Other guilds have been granted points, so I am guessing that this has to do something with our submission. Could you please validate this again?  https://twitter.com/blacklusion/status/1465766988916142090?s=20
2. We did take part in the ram change voting, but the report states otherwise.
3. We published an article covering the different projects that guilds are currently working on. However, we did not see any mention of this in the report. Could you please validate this or clarify why the article was not considered for the report: https://blacklusion.medium.com/wax-blockchain-overview-ae4ed8e943d

Thank you for looking into our appeal!

**Comment by blocksbarcelona** [comment]
Hi, answers below:
1) publishing update on social networks no longer grants points
2) we have added the point for RAM voting
3) one post is not enough to get points granted.
Keep up the good work!
