### ISSUE TITLE
bountyblok - January 2022 appeal

### ISSUE THREAD

**Issue by bountyblok** [wax-office-of-inspector-general/waxguilds#217]
Hi all,

1) Fulfilling monthly requirements:

We didn't get points for this and we did submit a post about it on January 15: https://bountyblok.medium.com/bountyblok-on-wax-december-2021-update-7a26d2ad76f2 it's also on the report's .md at the top.

I realize the title was wrong since we skipped December but we **just renamed**

bountyblok on WAX - DECEMBER 2021 UPDATE

to

bountyblok on WAX - DECEMBER/JANUARY 2022 UPDATE

2) Product 2 wax.drop.bountyblok.io:  Kindly review the points for the wax.drop.bountyblok.io tool (you can remove drop.bountyblok.io the url changed) this tool is heavily used by 350+ WAX NFT projects and growing, and quite popular in general

3) ED: harmoniagoya.io I just want to clarify that they are actually live on WAX since December - their actual game isn't live yet and they'll be releasing a beta soon. Their Discord community is nearing 4K members and is growing: https://discord.gg/aSehdvYa . They're constantly creating giveaways and engaging their community.

Thanks for your time, 
Dimitri

**Comment by kaefergeneral** [comment]
1.) Releasing a public report was not a monthly requirement for this evaluation.
2.) Points have been adjusted.
3.) We are waiting for some further progress here. But we have an eye on it.

Best regards,
your OIG
