### ISSUE TITLE
Hive BP - January 2022 appeal

### ISSUE THREAD

**Issue by hiveben** [wax-office-of-inspector-general/waxguilds#218]
Hi there, we probably didn't provide enough data. Let's fix that.

For NFTHive, we had 735 different buyers and 734 different sellers on the market, generating a volume of 288.3K WAX or $111K. We are falling behind a bit, which is why we tried to increase marketing. We applied for Google ads and Twitter ads campaign, but being an NFT Market, it often gets rejected. We finally found a way to advertise with dappradar though, which is on the roadmap for the next period. We are also hosting a WCW banner, advertising the waxbuyoffers feature.
It was important to upgrade the frontend first, where we put in a lot of the work this period.

Apart from buyers and sellers, NFTHive has a lot of users of its bulk tools, which offers transferring, burning, staking, unstaking, distribution etc. It's hard to measure exactly how many people are using it, but if you check https://wax.bloks.io/account/nft.hive you can see that a lot of the boosted transactions are not market actions, but inventory management related like: https://wax.bloks.io/transaction/4d53c201900c6e1b5738f95104ab93efc0453cac540872ec8c4bac2fbb40df59

On our Roadmap for the next period, there's more advertisement, as mentioned above. We are also continuing to improve the frontend with the help of our new developer. That sounds like an easy task, but NFTHive is huge and there are a lot of areas to cover, so it takes up quite some time actually. We're going to make global buyoffers more prominent, as it got much positive feedback. We are also preparing to roll out rewards for completing Sets on NFTHive. It will be called Honey, a currency for which we will release a whitepaper. But the idea is that honey can be used in minigames to win NFTs from supported collections. So you complete sets, get rewarded, have a chance to win ultra rare items from those sets etc. We hope to boost pure collectibles through this mechanism.
We are also planning to build our own drop and pack contracts, which we can offer to partners.

For the market template, we did add blending as built in feature. So collections that use blending can enable it by adding blending contracts to the config. This one done as the request by a collection.
Roadmap: Our Frontend Dev is currently in the middle of upgrading the code to modern Javascript standards, adds testing etc. It will be released within a few days and we hope to add it to the wax developer stack, so it can be more widely used.

WaxMarketCap: Number wise it's doing really well. We've got 11.27k unique visitors this months, according to cloudflare analytics.
Roadmap for the next period: Rolling out User Analytics

Community and Marketing:
Some examples for our marketing on Twitter (>15K followers now)
https://twitter.com/nfthiveio/status/1479900524367335427
https://twitter.com/nfthiveio/status/1478836573621866503
https://twitter.com/nfthiveio/status/1478742404555493376
https://twitter.com/nfthiveio/status/1476944192597200899
https://twitter.com/nfthiveio/status/1475523090276749321
https://twitter.com/nfthiveio/status/1473039814110945281
https://twitter.com/nfthiveio/status/1470829133152153602
https://twitter.com/nfthiveio/status/1471491036820033549

There are lots of retweets for collections and wax, too, as well as general engagement and it's all about WAX. Overall we crafted 155 Tweets, had 151k Impressions, 31k visits and 2500 mentions in the last 28 days

We also dropped to 0 for Channel management. I didn't provide an update here, mainly because nothing has changed. I'm still active in various telegram groups, discord, wax official, have people DM me about wcw issues, staking, engaged in chats, managed WAX Unofficial Telegram, managed the Street Fighter channel during the SF 3 launch, where a mod went rogue and started banning and deleting half the channel. Not sure I need to mention this stuff every month.

Community tools also went down. Hive-E has 300 users, has been updated and stabilized. On the roadmap is adding a buy offer notifications, eg there's a new buy offer for your NFT (if it's a good one).
I think all the sales feeds in wax discord, on twitter and telegram should count as well.

**Comment by blocksbarcelona** [comment]
Thank you Ben for providing the analytics and milestones. We have adjusted the points on your projects.
