### ISSUE TITLE
EOS Amsterdam - January 2022 Appeal

### ISSUE THREAD

**Issue by yannickeosams** [wax-office-of-inspector-general/waxguilds#219]
Dear IGs,

This evaluation we received 0 points for the "Creation of original informational content or translation that benefits WAX" criterium, even though our content has remained to be an important asset to the overall WAX documentation and has been awarded multiple points in every past evaluation. We assume this is a small mistake and wanted to raise awareness.

**Comment by kaefergeneral** [comment]
We moved your points from "Creation of Content" to "Building and supporting community tools".
But we also went ahead to add you one point under "Creation of original content".
