### ISSUE TITLE
NiFTyLIFE January 2022 Appeal

### ISSUE THREAD

**Issue by Roy-NiftyLife** [wax-office-of-inspector-general/waxguilds#221]
Please accept and allow the following information to supplement NiFTyLIFE’s January 2022 guild report. We are creating an internal template thus going forward our report’s will include at least as much detail you find herein, as requested by the OIG, and as gleaned from the successful reports of other guilds. We will also be establishing an analytics URL to automatically track things like user metrics, defi contributions, and other information as it becomes available.

# Product 1 - Waxstash.com

Current status: Waxstash.com marketplace is an active WAX marketplace merging simpeleasset and atomicasset standards. WAX has in the past published links to waxstash on their NFT release websites as one of the go to secondary markets. However, sometime within the last couple of months they stopped doing this, I was not contacted about it and am unaware of exactly when or why, but this has led to a significant decline in traffic to waxstash. Nonetheless, I prefer not to push the current waxstash.com as my focus is on building waxstash.io. Waxstash.io is a completely new build from he ground up and it will include all atomicasset features, such as auctions, drops, markets, set building, simpleassets bridge, bulk tools, landing pages, explorer, NFT creation, plus more, and will merge some of the more popular simpeleasset collections and token packs. As reported in the past this is a long term build, progress to date and next milestones are discussed below. 

## Progress

Our development progress can best be measured by stages of module completion. Each module represents a fully functioning waxstash.io feature or a set of functions shared across the app by all modules. Thus completed modules represent significant progress towards a fully automated user facing UI & UX functionality for waxstash.io.

The following modules are completed or in progress:
- Authentication Module. Complete. Four services for authenticating with chosen wallet, checking API health, and automatically determining app wide RPC and Atomic API endpoints. Shared across entire app.
- Collections Module. Complete. Three services responsible for retrieving whitelists, and then the top 100 verified and whitelisted collections by 3 day volume, and for searching additional collections. Shared across entire app.
- Default Collection Module. Complete. Service allowing a user to set their collection of choice as their default collection, so that whenever they load waxstash.io without any other parameters, their default collection will load instead of general results.
- Material Module. Complete. Compiles all needed material components to share across the app.
- Filter Module. 60% progress. App wide module to present the appropriate filter UI for searching assets through the explorer, marketplace, or user inventory.
- Marketplace Module. 40% progress. Full featured marketplace UI implementing all of the above modules.
- Explorer Module. 10% progress. Atomicassets explorer UI implementing all of the above modules.
- Inventory Module. 0% progress. Viewing account inventory will be shared with most other modules.
- Landing Page Module. 0% progress.
- Data Module. In progress. This module supports the various http requests needed to support the app and deals with caching recent responses to reduce load on the network (a repeat request will be retrieved locally instead of sending a query over the network). Currently this module retrieves and caches sales listings data and will be expanded as more data is needed for additional modules, such as inventory, explorer, and collection filters.

## Next Milestones

- The top priority for this product is to launch a minimally viable UI, which at this time is expected to include all modules and functionality needed to fully support the marketplace, explorer, and inventory features. When those modules are fully complete waxstash.io can be launched. Expected in 30-60 days.
- Dedicated server tracing all collections and serving an API providing dynamic filters for each collection. This API will be required for waxstash.io to function. Each collection will at all times have custom and current filters available for waxstash.io and packbreaks.io. Required prior to initial launch of waxstash.io.
- Start next waxstash.io feature modules and additional modules to be determined. Such as bulk tools, set building, auctions, drops, etc. These modules have not yet been started. Once the initial marketplace and explorer features of waxstash.io are launched, many of the support modules needed for these additional modules will already be complete, thus adding these additional features will require less time.
- Before our next report we will be fixing our dapp radar tracking, since it currently seems to be broken.
- A more robust image server. Since creating our image server to resize and cache NFT images from our IPFS node we have determined a more efficient method is possible. We plan to implement changes into a new server and let it automatically search for newly created NFTs so they can all be resized and cached.  
- A user metrics URL and or user interface, perhaps built into the waxstash.io landing page.

## User Metrics

In addition to metrics data already reported in our January 15th 2022 report:
- 114 unique users performing 1082 actions on our wax.stash contract.
- 479 Atomicassets sales across 414 unique buyers & sellers
- 27743.78948040 WAX sales volume through Atomicmarket contract
- 554 WAX contributed to WAX defi from Atomicassets sales

# Product 2 - Packbreaks.io

Current status: Packbreaks.io is currently active with a packbreak feature and a repack feature.

## Progress
According to our expected progress we developed a repack contract that allows users to ‘repack’ 10 NFTs into a pack, to be sold as 10 slots. Each time a slot is purchased all slots are shuffled twice. When the 10th slot is purchased all slots are shuffled twice one last time, then all NFT asset_ids are shuffled twice, and then the slots and asset_ids are shuffled together. This randomly assigns asset_ids to slot_ids and then the NFT’s are airdropped to their respective slot owners.
- Current progress is complete. The contract, the website updates, UI, and UX are complete and users are starting to create repacks.
- The repack contract features an on-chain leaderboard, tracking account data for the numbers of repacks or slots sold or bought, as well as the total earned or spent. Each time a repack opens, points are tallied for each participant according to how the participated.

## Next Milestones

- Within a couple of weeks we will start to hold repack giveaways based on the on-chain leaderboards. They will be announced on twitter and on WAX discord.
- Currently there has been a bit of attention from users creating repacks but not much from slot buyers. This is because users creating repacks are approaching it the wrong way and are not including enough, or good enough, NFTs to entice slot buyers to chase the repack. We plan to personally create some top repacks that are more like giveaways. Repacks loaded with mostly top NFTs instead of 9 commons of some low volume collection. But I expect this means I will have to change the contract in order to prohibit one account from buying up all the slots.
- Universal pack breaker. We have learned that users love packbreaks on newly dropped projects but that after the initial buzz of the new pack dies off, or most of the packs are opened, the pack breaker for that pack is largely unused. The next update packbreaks will get is a universal pack breaker, so new projects can be supported on the fly, and then turned off once the buzz dies down, and then the next project drop turned on and so on. The existing pack break contracts would be retired, to make room for packbreaks to be a universal breaker for newly dropped popular packs on one side, and the repack feature on the other. Packbreaks.io just received an update with the repack contract so the universal contract won’t be started at least until the initial version of waxstash.io discussed above is launched.

## User Metrics

In addition to metrics data already reported in our January 15th 2022 report:
- 39 unique users accounting for 930 actions, which may include creating a repack, cancelling a repack, changing the price, or buying a slot. Some of these actions were testing done by us.
- 31 repacks are currently live

**Comment by kaefergeneral** [comment]
Points have been adjusted.
Hope to see you back on the roster with the next tech evaluation!
