### ISSUE TITLE
Blacklusionx - Appeal January 2022

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#222]
This month we don't have much to complain about: 
I just noticed that we got credited 2 points in the Oracle Category, even though this can only score a maximum of 1 Point as far as I know:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/51051978/151671863-2643d086-01bd-4f5b-86b6-5691ef834479.png">

While we are at it, could you please update some information in the Notion:
- Update the guild logo to our new one (pick the format you need): https://blacklusion.io/resources/
- Update email to: contact@blacklusion.io
- Update telegram to: @Blacklusion

Thanks for looking into this!

**Comment by blocksbarcelona** [comment]
Thank you Leonard!
