### ISSUE TITLE
BlokCrafters - January 2022 Appeal

### ISSUE THREAD

**Issue by bdizzle32** [wax-office-of-inspector-general/waxguilds#223]
Hello OIG's
We would like to Appeal our score in Tech-ops, Ecosystem Development, Product Development & Community Engagement

Technical Operations - We feel we should be awarded at least 1 point for providing useful APIs.  We have provided the Atomic Assets (and Market, and Tools) since near the beginning of the AA API.  We had a few issues with handling too many requests during the early part of the evaluation period but these have now been dealt with and our Atomic APIs are running well again - Assets, Market, and Tools.

Ecosystem Development - We would like to appeal our score in this category for higher than 0.
NFT Origins is an active service, we have already launched 1 collection and are actively building 2 others that have not been announced yet. 
Collections launched so far https://waxmarketcap.com/collection/tangiblenfts 
https://tangiblenfts.io/home 

Product Development - We would like to appeal our score in this category. 
MyNifties app Was Rejected due to the following reason by apple:
[Blokcrafters_Appeal-MyNifties.pdf](https://github.com/wax-office-of-inspector-general/waxguilds/files/7964628/Blokcrafters_Appeal-MyNifties.pdf)

Guideline 3.1.1 - Business - Payments - In-App Purchase
We noticed that your app includes or accesses paid digital content, services, or functionality by means other than in-app purchase, which is not appropriate for the App Store. Specifically:
- Your app accesses digital content purchased outside the app, such as viewing or importing included externally purchased NFTs, but that content isn’t available to purchase using in-app purchase.
Next Steps
The paid digital content, services, or subscriptions included in or accessed by your app must be available for purchase using in-app purchase.
Apps that offer paid digital services and content across multiple platforms may allow customers to access the content they acquired outside the app as long as it is also available for purchase using in-app purchase. See Guideline 3.1.3(b) Multiplatform Services for more information.
If you have any additional information to provide regarding the digital content and services in your app and how the guidelines apply to them, please reply to this message in App Store Connect and let us know. If there is information you’d like us to consider in our review of future submissions, please feel free to include it in the App Review Information section of App Store Connect.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Due to apple misunderstanding the screen grab they attached within the rejection we have realized the error of the rejection. Based on the screen grab they believe we were facilitating transactions instead of displaying(tracking) accounts for users. For this we have resubmitted the application with the word “tracking”, this will clear the rejection and allow MyNifties to be available on the app store.

Community Engagement - We would like to appeal our score to be higher than 0 in Community management initiatives e.g. channel administration, awareness building, teaching and mentoring (0 to 2)
please take a look at our Youtube channels videos, there are many guides and tutorials.
We also are active in the WAX discord channel. Dylan is there daily assisting people as he is also a part of the WAX team. 

Links to youtube.

https://www.youtube.com/c/BlokCrafters/videos

WAXMarketCap.com - Analytics for Tangible NFT's
Top Performing NFT Collections on WAX.io - Marketcap, Volume, Change, Floor Prices, Market Links & 7 Day Performance
	https://waxmarketcap.com/collection/tangiblenfts

**Comment by kaefergeneral** [comment]
Dear Blokcrafters,
right now we are scoring these services based on provided information and launches.
Scores for the "Tangible" release have been credited in the past and are based on different metrics. 
Given that the drop is past and does not have any ongoing engagement and a volume of roughly 100 trades accounting for less than $1000 over the evaluation frame, we don't see fit to credit additional points. 

We added points for providing atomic API for the evaluation frame, but given the downtimes, over the last weeks, you need to be aware that you might lose those points again during the next infrastructure evaluation if the service is not upheld.

Unfortunately, we can't credit scores for an app that is not available and / or not working properly as it's the case for the versions currently used for testing by the OIG. We will need to await significant development progress to credit a score for MyNifties again, as it has been in development for a very long time without significant progress.

As for your appeal in regards to community management, you have been credited points under the "creation of content", but you need to improve the distribution of your content as it has little to no reach.

Kind Regards,
your OIG
