### ISSUE TITLE
Wizards Guild January 2022 appeal

### ISSUE THREAD

**Issue by BigMike690** [wax-office-of-inspector-general/waxguilds#224]
We didn't include enough metrics in our original report. 

DU$T sent out over 300,000 DU$T rewards this month. 

We have over 17,500 token hodlers who generate approximately 75000 transactions every week, and 10,700 tx's every day. 

The DU$T miner bot is in over 100 chats mostly from the wax community 

Some of our bigger partners include: 

Alien Worlds
The Horrors
Blockchain Heroes
HodlGod
ExitLimbo 

Roadmap:
-Distributing DU$T to other collections starting with Nifty Wizards Q1
- Collection staking for distribution power Q1/2
-Dust staking - nft reward pool Q3

Nifty Wizards 

We have about 100-150 active players daily and 250 active monthly users. 

We just completed our third Battle royale contest and we had our largest turnout ever at 48 participants. 

Roadmap 

- NPC bosses Q1
- New Spliff blends Q1
- Discord bots Q2

Shyn 

We have over 1000 downloads on both IOS and Android and we are working on adding analytics to the app so we can get MAU/DAU numbers. 

Roadmap 

- We have a new UIX currently in beta with an imminient product release
- We have filters in the new UIX for power users. 
- We are working on adding more collections for Ethereum and Flow so we can attract a wider audience to SHYN and expose them to WAX.

Collectabot 

Collectabot gets between 60 -100 calls per day and we had a very large spike this month in calls at one point which put us at a whopping 3.3 million calls this month. 

Roadmap 

- Update infrastructure to make it more robust based on Shyn infra Q1
-Add more wax collections to collectabot. Q?

**Comment by kaefergeneral** [comment]
As per the data we have been provided with, neither Dust nor NiftyWizards provide a significant impact on the WAX ecosystem to justify a higher score. We evaluate projects based on the following criteria:

- Utility, what does your product solve for our end-users.
- Innovation, what does your product provide no other product does. (supported by usage metrics)
- Contribution to WAX DeFi, does your product contribute to a significant extent to the WAX tokenomics? (trade amount and volume)
- On-boarding, does your product draw new users to the WAX ecosystem? (user metrics)
- Technological advancement, your product applies new technologies and provides tools and/or documentation supporting developers within our ecosystem.

Right now, none of your products check in any of these categories.

These criteria need to be supported by accurate progress reports and development plans.
In the future, we urge you to limit your reports to the current evaluation period and not submit a multi-page long report that is mostly a copy of the previous month and proves inaccurate.
Take your 'Collectabot' submission that has been unchanged for a long time as an example. 
For over half a year, with every evaluation, you reported that "Other sets have reached out to us to implement the bot with their set, and integration is ongoing.". But to this date, we have not seen any further integration.

Please also refrain from trying to bolster your report by claiming 'bigger partners' you have no ongoing relationship with, aside from your dust bot running on their community channels.

We will revisit Shyn as development progresses. But be aware that we have multiple feature-rich NFT Viewers on WAX already that are further advanced and established, while the usefulness of NFT Viewers in itself is already very limited.
A multi-chain viewer is a new angle but will have to prove its worth.
