### ISSUE TITLE
3DK Render Guild February Appeal

### ISSUE THREAD

**Issue by 3dkrender** [wax-office-of-inspector-general/waxguilds#257]
DelphiOracle: We have added today the WAX-ETH pair in the price update publications. The new pair is operational at the time of writing this appeal.

Testnet APIs reminder: Our guild has a full history API on testnet as well as an API for AtomicAssets.

- Atomic API: https://testatomic.3dkrender.com   (since January 2022)
- Full History: https://testnet-wax.3dkrender.com  (since February 2021)

**Comment by kaefergeneral** [comment]
Noted :)
