### ISSUE TITLE
WAXUSA February 2022 Appeal

### ISSUE THREAD

**Issue by eosusa** [wax-office-of-inspector-general/waxguilds#258]
Looks like we did not get credit for providing testnet history services (test.wax.eosusa.news) even though it was denoted in the Feb22 update.

Also not 100% sure about where many of our drop/scoring tools might fall into the listings as they aren't listed under the ProdDev section individually or seem to be rolled into the NFT Solutions category.

**Comment by rakeden** [comment]
Hello @eosusa  

we've made adjustments and granted 1 point for `testnet-history`.

the OIG team
