### ISSUE TITLE
EOSphere Guild February 2022 Appeal

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#260]
Good-Day OIG's

Three requests for review this month if you wouldn't mind.

1. We have updated our number of **oracle price feed data points** to four
2. We provide V1 and V2 **Full history on WAX Testnet**, it is also advertised on our bp.json
-  https://eosphere.io/chains.json -> https://eosphere.io/waxtestnet/bp.json
-  https://wax-testnet.eosphere.io/v2/health
3. We have advertised our ability to provide **commercial history and API solutions** 
- https://medium.com/eosphere/eosphere-guild-february-22-update-dbd0e46859c1

![image](https://user-images.githubusercontent.com/12730423/158011953-66f7c457-9788-412e-9ecc-edb7a844a86d.png)

**Comment by rakeden** [comment]
Hello @Rossco99 

after revisiting your report and ratings we've decided over following adjustments:

- Add 1 point for `testnet-history` solution
- Add 1 point for `commercial history solutions`
- Add 2 points under `ecosystem-development` for your educational content

Cheers
