### ISSUE TITLE
WeCan February 2022 appeal

### ISSUE THREAD

**Issue by We-Can-dev** [wax-office-of-inspector-general/waxguilds#262]
Hello IG,

Our Testnet Hyperion v1/v2 endpoint https://hyperion-wax-testnet.wecan.dev/v2/health wasn't counted in this period.

We've mentioned it in our report https://github.com/wax-office-of-inspector-general/waxguilds/pull/250/files#diff-ac9e71a218022b914587c220d8e2547005bda592ba4059673a5dd809d8a5083cR13

Here's the (our Testnet Hyperion was started a week prior we created a public status page, though) 3d party check (uptimerobot.com) that shows the endpoint uptime history for our Testnet Hyperion https://status.wecan.dev/790616947

Thank you!

**Comment by kaefergeneral** [comment]
Noted and adjusted. :)
