### ISSUE TITLE
Wizards Guild March 2022 Appeal

### ISSUE THREAD

**Issue by BigMike690** [wax-office-of-inspector-general/waxguilds#263]
Wizards Guild March 2022 Appeal

- Version 4.0 Guidelines include 5 products. We submitted 5 products but were only rated for 3. Please rate both Shyn and DU$T as well.

- History node: Our history node is http://wax-history.wizardsguild.one/v1/history/ as is stated in our bp.json. Please ensure you are using the appropriate URL, other routes will not yield any history results. History information is as stated below.

BP JSON
https://wizardsguild.one/bp.json

HISTORY NODE
   {
      "location": {
        "name": "wax-history",
        "country": "US",
        "latitude": 37.403,
        "longitude": -124.1811
      },
      "node_type": "query",
      "features":["history-v1"],
      "api_endpoint": "http://wax-history.wizardsguild.one",
      "ssl_endpoint": "https://wax-history.wizardsguild.one"
    }

API NODE
   {
      "location": {
        "name": "wax-query",
        "country": "US",
        "latitude": 37.403,
        "longitude": -122.1811
      },
      "node_type": "query",
      "api_endpoint": "http://wax-bp.wizardsguild.one",
      "ssl_endpoint": "https://wax-bp.wizardsguild.one",
        "features": ["chain-api", "account-query"]
    },

![wizardsguildrouting](https://user-images.githubusercontent.com/87723836/158075968-b705f53d-2edd-4e44-aac8-de067ffbfa78.png)

Our load balancer manges all incoming routes based on subdomain

- wax-history.wizardsguild.one solely for history and not an api node, and can be referenced from bp.json as such.

- Any route starting with /v1/history/* will direct into our history infrastructure only from the wax-history subdomain /v1/magicdust is not a valid route.

- Other routes outside of /v1/history would not be considered as history when it is not stated in our bp.json. 

- This is not an API node, nor should it ever be considered for API calls, it simply is used for history.

- **Any chain api calls are routed to a fallback node and if unable will route to a random bp since this is not an api node.**

- We did not know this was not allowed unless with exclusive permissions, we can ask for permission moving forward and make sure any ones with no permission are not a part of the fallback procedure. 

- wax-bp.wizardguild.one is solely for chain api calls, account queries and pushing transactions, also referenced in bp.json

- Any route starting with /v1/chain/* will direct into our api infrastructure

- Any route starting with /v1/accounts/* will direct into our account api infrastructure

- It is not a history node, so no routes to /v1/history/* are considered to be valid on on our API endpoint, and can be referenced from bp.json

- Any P2P will route to our corresponding query node pipeline

- We are failing a history node requirement but we are shown a chain api failure which is not even a subdomain that corresponds to chain API. Clearly it is stated that the subdomain wax-history is only a history api and only should be used as such and can be referenced over from bp.json

- Ledgerwise snapshots show the history node as active and available throughout the whole entire evaluation and still is fully functional. 

- These were tested as a verified method of making sure history was working

get_actions
get_transaction

**Comment by kaefergeneral** [comment]
During our evaluation, your history node was not responding.
As the history plugin is reliant on the chain-api plugin, in the case of a failing manual history check, we always test the chain-api plugin to see if the history node itself is available. This resulted in the exposure of your malicious routing behavior.
It should not be required to route the chain-api calls to a fallback node. But even if, any of your fallback nodes should be able to handle the request. Routing valid requests to random bps, without informing them or having agreements in place, is definitely not tolerable, especially to the extent you practiced it.

Furthermore, your routing, other than claimed, was definitely not random. All of our calls resulted in the same redirect, even when the redirect was failing.
Asking the guild to unban your IP also magically fixed your history for us.

Given your track record of misrepresentations, the changing explanations with every proof we gave you, the flimsy performance after you supposedly fixed the routing, we can not rely on the claim of your own working history for the evaluation time frame.

Be as it may, bombarding the infrastructure of other guilds with hundreds of thousands of requests for over a month is not acceptable, and we stand by penalizing this behavior.

If you disagree with this decision, we are open to a public discussion involving established guilds.
