### ISSUE TITLE
BlokCrafters February 2022 Appeal

### ISSUE THREAD

**Issue by blokcrafter-dan** [wax-office-of-inspector-general/waxguilds#264]
Hello OIG's

We would like to Appeal our score in Technical Operations, Product Development and Ecosystem
Development.

Technical Operations -
We would like to appeal our score of 0 for test-net history solutions.  We have been
consistently running both v1 and v2 history on test-net for a while now.  Both have been
stable and up to date this past rating period.

Product Development - We would like to appeal our score in this category for the product MyNifties
- We read the guidelines and understand we require 3 data points to be eligible to be rated for this product - they are:

MyNifties: current last 30 days development update
    This Release - (2.2)
- Improved Add account made it load faster by improving the back end API
- Delete Account bugs crushed
- Faster Account Load and UI enhancements
- Displaying Wax Value in $ on every app view.
- Collection load faster by improving the back end API
Known Issues: Images for movies are not displayed

Next IOS Release:
    - Fix Movie images to Load
    - Account name avatar displayed
    - Other bug issues may come from Release 2.2

We are planning to have Bi-weekly releases for Bug Fixes and improving the UI experience
Future/Every release Plan:
    Marketing the app for adoption for Wax community
    Finishing Android Version and deploying to android app store.

Ecosystem Development - We would like to appeal our score in this
category.

We have added a new team member to our guild his name is Gabriel, he has improved our quality of content creation. Please take a look at our last rating periods content.
https://www.youtube.com/c/BlokCrafters/videos
also here is a list of all the new content we have created during this last rating period.

Youtube videos
https://www.youtube.com/watch?v=SN61s3Eaqt8&t=2s
https://www.youtube.com/watch?v=XY9KlVxiVOs
https://www.youtube.com/watch?v=qte2_wezuME&t=194s
https://www.youtube.com/watch?v=zXKEFaOiD_w&t=34s
https://www.youtube.com/watch?v=HKq-8bckzdk&t=31s
https://www.youtube.com/watch?v=M87C5FnfyJI&t=266s
https://www.youtube.com/watch?v=aW7_tu-erWU
https://www.youtube.com/watch?v=7wGlHX3jYHE&t=4s

Twitter posts sharing YouTube videos
https://twitter.com/blokcrafters/status/1501287881494740998
https://twitter.com/blokcrafters/status/1499471498297458689
https://twitter.com/blokcrafters/status/1494004409784803334
https://twitter.com/blokcrafters/status/1494357045268647941
https://twitter.com/blokcrafters/status/1490853114722717697
https://twitter.com/blokcrafters/status/1486788292469211145

Dylan also hosted many twitter spaces for WAX Wednesday's
https://twitter.com/WAX_io/status/1486023687434211328
https://twitter.com/earwaxio/status/1472768910395154433
https://twitter.com/WAX_io/status/1486473357554028548
https://twitter.com/KryptoKumas/status/1489064562590732290
https://twitter.com/bretblackberg/status/1491600323957428225

YouTube analytics are at:
https://github.com/blokcrafters/public/blob/5db6d1aa55669cb68b43c11c6142b23965d67c12/images/Image%20from%20iOS%20(23).jpg

iOS App Analytics:
https://github.com/blokcrafters/public/blob/8815a9c48c1305e2bd2045532529d3a3a60809b0/images/Screen%20Shot%202022-03-12%20at%202.40.49%20PM.png

Thank you,
The BlokCrafters Team

**Comment by kaefergeneral** [comment]
Hi BlokCrafters,
unfortunately, we can not credit you points for testnet as neither v1 nor v2 are operational at the moment.
This will be revisited on the next technical evaluation.

MyNifties:
We tested the latest version and it was not functional. Even if it were, it was, at this stage, it would likely not warrant points due to the limited distribution and functionalities that do not add anything beyond what existing products already deliver.

We granted you points for your efforts on Youtube and Twitter, but also need to urge you to improve the quality and distribution.

Best wishes,
The OIG
