### ISSUE TITLE
bountyblok - April 2022 appeal

### ISSUE THREAD

**Issue by bountyblok** [wax-office-of-inspector-general/waxguilds#302]
Hi IGs, 
 
Our Product "Contests by bountyblok" was added as "Released" but there's no points. However we have seen projects "under development" get points so looking for clarifications how this part works? 
 
It is indeed a new site into production, and is being tested right now by various teams including WAX core team: 
 
https://bblk.io/2uBy (WAX Team) 
https://bblk.io/AnmA 
https://bblk.io/dYav 
 
Will include metrics in the next weeks and months to come. 
 
Thanks, 
Jackie

**Comment by kaefergeneral** [comment]
Hi Jackie,

due to the timely release one day before the cut-off period and most contests being scheduled for the coming evaluation period, we were undecided on the scoring.
We credited you a score for now and will re-assess with the next evaluation once we have some more metrics.

Best,
OIG
