### ISSUE TITLE
WAXGalaxy Appeal - April

### ISSUE THREAD

**Issue by sukeshtedla** [wax-office-of-inspector-general/waxguilds#303]
Hi Guys,

Thanks for doing awesome work. Special thanks to Kaefer for helping share valuable feedback after testing our services. Unfortunately, this month we missed out on our CPU requirements and missed the minimum points. But we are trying to do a lot of important things to support the ecosystem and hopefully, you can see that in our work.

As part of this evaluation period, we would like to appeal on the following points:

1. Our product Kryptoskatt: We understand that there are some issues that were highlighted and we are actively working to fix them as we grow. But we want to emphasize that we are the only service today supporting the WAX community with their TAX needs by offering personalized services in the industry. Since the public launch in January, here are some stats:

- We have gained more than **350+** users to date, growing by 3-4 users daily, completely organic.
- **85+** WAX accounts are added to the system
-  Offered paid support to 2 customers who had more than 100k transactions and 1 other in progress at the moment. We fetched price histories for different WAX specific tokens and supported these clients. 
 
We are still in the early days, there are a lot of things that need to be developed so that it can be a self-service offering for the users. But in the meantime, our goal is to continue the personalised support and improve the platform based on the feedback.

**Our appeal to the IGs is to consider this as a Service and would like to request the points accordingly.**

2. Our Content Contributions(developers.wax.io): We took the initiative and started putting together very detailed guides that help anyone with basic knowledge to get started with setting up WAX Infra. We are actively updating them based on new changes and looking forward to adding more guides as well. In addition, we have been tracking the DeFi stats every single epoch and posting them on our website.

**We would like to appeal to the IGs to consider increasing our points for content creation.**

3. History Services: We have been supporting multiple Daaps in the ecosystem today for almost **10 months** now with our Standalone personalized history services. Our API subscription services since the launch last month have seen interest from 6 Apps so far. We are the only one offering both types of services today. We are adding new projects every month and making regular improvements to the service.

**We would like to appeal to the IGs to consider awarding full points for us in this category.**

4. Telegram Bot: We are the only ones running the bot for more than 18 months and are monitoring more than 2000+ accounts currently and growing every single day. We are working regularly to add new features and maintain it on a daily basis. 

**We would like to appeal to the IGs to consider awarding full points for us in this category as its one of the important product in the ecosystem .**

Thanks for your work. We would be glad to answer any of your questions.

**Comment by kaefergeneral** [comment]
Hi Sukesh,

**Kryptoskatt**
After some more tests and lengthy internal discussion, we concluded that the service is not yet in a state where we can start crediting points again. Given that it received a score as 'product in development' for over half a year already exceeding our usual limits, we can not grant any further scores at this point. If you announce the tax service publicly and serve more clients we might be willing to consider it as an ongoing service, but not at this stage yet.

We acknowledge the progress made. Unfortunately, the whole system is still too unstable and has too many bugs to be used for what is intended.

As for the added metrics, keep in mind that only users that are coming from/for WAX matter to us. So what would be of interest for us would be how many users you have that track WAX accounts, not total users or total WAX accounts.
The next step would likely be a success rate of who is able to use the service winningly.

**Content Contribution**
Your content contribution has already been honored with points.

**History Services**
As far as we are aware, you are not the only one offering both types of services. But also have been honored already as one of the highest-scoring service providers in this category.

**Telegram Bot** 
Unfortunately, how long you operate the bot does not matter for the evaluation.
We agree that the bot indeed does add value to the ecosystem but already scores almost the same as WAX Authorities bot that has a few more essential events it reports on.

It is also to note that you are already receiving more than what we intended as a score for individual bots. As such you are receiving more than full points.

Thanks for the input. 
We hope to see you back in a standby seat with the next technical evaluation.
