### ISSUE TITLE
Blacklusion - April 2022 Appeal

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#307]
Hey IGs,

First up just some general questions about the product sheet:
- Can you please remove the "NFT Stats", since this is nothing we are currently working on or getting points for
- Validationcore: It says that it is decaying in Feb 2022. Obviously, we are over that anyways already. I just wanted to double-check on the decaying on this, since we are still actively maintaining it and adding new features. It would be great if you could update this as well
- You can also remove the Exchange Contact, as this is something that fell flat months ago

Regarding the History: I understand that we had some issues this month, but could you go into the scoring of this a bit more: If I understand correctly v1 grants 1 point and v2 grants 2 points. We have been offering v1 most of the month and v2 about half of the month. Wouldn't that grant a total of 2points instead of 1 point?

Thank you for looking into this!

Cheers,
Leonard

**Comment by blocksbarcelona** [comment]
Hi Leonard, we have removed the old projects and the decay notice. V1 grants 1 point and V2 grants 1 point. If you have both, you got 3 points. We dont grant half de points for half de performance, sorry.
Keep up the good work!
