### ISSUE TITLE
TokenGamer - May 2022 Appeal

### ISSUE THREAD

**Issue by beasteh** [wax-office-of-inspector-general/waxguilds#349]
Hi OIG,

Thanks for the review, there's a few points that we would like to be reconsidered. 

1. We believe that our confidential submission (on email and mentioned in the report) was missed. This was referenced in the report as "9 Lives Arena" - so I guess it's not that confidental! However, the effort on our part was significant (multiple calls, emails and meetings) and I believe at least 1 member of the OIG can verify this.

2. Although not explicity requested in our report, we would like our YouTube and Twitch be considered as seperate, new products. Both of these were missed. Both are significant new ventures for Token Gamer. We will feature WAX games multiple times per month and these products will bring in gamers from other chains to WAX... they already have. Forge Arena and Blockchain Brawlers were featured on our first stream, and we had over 100 average viewers (many people had never heard of WAX) - the response we got to Forge was great! VoDs are available on YouTube for verification of quality.

Many thanks,
The Token Gamer team

**Comment by rakeden** [comment]
Hi tokengamer,

thanks for the feedback!

1. We evaluate ED contributions based on results. Deals that are not completed, can't be rated properly on our end. So therefore we can't grant points for "9 Lives Arena".

Please refer for the following criteria on ED/PD:
- user onboarding
- DeFi contribution
- measurable market impact (SC actions, user onboarding, ...)
- We'll expand on that until the next evaluation period

2. We are not granting points for both channels yet, as we see the product is still in early phase. We will revisit once the channels gain more attention and VODs are regularly released on both channels. Currently there are 4 VODs available for the past 4 weeks. Please consider resubmitting for the next evaluation period.

cheers,
WAX OIG
