### ISSUE TITLE
EOSphere - May 2022 appeal

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#350]
Would you mind reviewing our score in relation to the following services that we provide:
 - ES Repository API Snapshot Service (Mainnet)
 - ES Repository API Snapshot Service (Testnet)
 - ES API Snapshot Support Group
 - Nodeos Snapshots
 - Nodeos Blocks Backup
 - Atomic API Backup

In reviewing our score in relation to other Guilds we have noticed some are scored in *Building and supporting community tools and some in *Engagement for a few of these services.

We would like to ensure that we are effectively updating the OIG on our services in the correct section that have the associated incentivised weighting.

**Comment by kaefergeneral** [comment]
Thanks, 
we had an ongoing discussion on where and how to categorize these snapshots as they were not currently covered in our report layout. We now came to the conclusion to score them under 'Ecosystem Development' going forward. Other guilds that have been granted points have been adjusted accordingly.

Best, 
Kaefer
