### ISSUE TITLE
Ledgerwise - May 2022 Appeal 

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#351]
Hi OIGs, 

Thank you for the review. 

LW wish to appeal to recheck our scores for 

1. ES Snapshot Service - We are providing ES Snapshot Service as a backup to EOS-Sphere. But feel our scores are not matching them. 
We are given 12 points for our Service, please reconsider them. 

Please check https://ledgerwise.io/snapshots/

2. NFTVT.IO - we are working on NFT Stats and Activity based marketplace, the product is up and running. We are not awarded any points for this product as well. 

NFTVT.IO 

shows changes in volume, sales and prices in different time frames. 
Shows sales, mints, auctions happening in real time. Show marketplace for both collections and templates. 
Show's portfolio. 
Compares wallets holding certain collection with other collection. 
Shows top template for certain collection. 

We have changed the UI on Saturday, and are bringing more changes on how people could analyze certain collection, and templates.
Ability for users to follow others wallets and get notified on website/TG. 
Ability for Ninja NFT Traders to earn giving signals or information about their investment strategy. 
Ability to put a limit on certain template. 
Ability to buy and sell NFTs. 

3. WAXZILLA.IO 

We were not evaluated for WAXZILLA. WAXZILLA wish to be something similar to producthunt where community members could come up and upvote different products/ideas. It aims to be centered point for community to talk about new products, build team, get traction and maybe funding. 

We will allow only verified users with passes to upvote product or interact with Smart Contract. The users may get free drops for upvoting the products/ideas. 

WAXZILLA.IO is live on testnet. You may interact with the smart contract. If you wish to interact as an user we will drop you a pass, just DM on telegram. We have testing and bringing new changes but the basics has been covered for now. 

Also any help to get Guilds products/services on Zilla will be a great help for WAX Ecosystem, as we don't have centralized place for what all is happening on WAX. 

I know you guys understand that development takes time, and we couldn't just come up with great working products in month time. We are working hard here - hopefully you will consider our hard work and give us fair points. 

Thank you, 
Tanish

**Comment by rakeden** [comment]
Hi Ledgerwise Team,

1. we've revisited your snapshot service and moved it to ED accordingly with other guilds. That has increased this criteria rating from 12p to 18p.
2. After visiting nftv.io we've concluded that the product is still in development, data is incomplete and the interface could need an overhaul to become more informative. We are not granting points for nftv.io yet. Please resubmit the product again in the next evaluation period.
3. We consider WAXZILLA.IO being still in Development, although it can be tested on testnet. We advise you to launch the product on wax mainnet before submitting it for your product sheet. We will grant points for it once it's used in production!

Note: We've removed the penalty for CPU latency, as it was a mistake on our side, sorry.

cheers, 
WAX OIG
