### ISSUE TITLE
Defibox - May 2022 Appeal

### ISSUE THREAD

**Issue by DefiboxTeam** [wax-office-of-inspector-general/waxguilds#353]
**Greetings, OIGs**

Thank you for your feedback on the monthly Guild Review. Here is some points we would like to ask:
1. About OIG meetings, is it possible to arrange a meeting on this Monday or Tuesday? Because we were kind of delayed for basic server setup, so our meeting also missing. Highly appreciated if OIG official can help this.

2. About the blog introduction of wax guild candidency, here it is: https://defiboxteam.medium.com/defibox-announces-its-wax-guild-candidacy-495364080fa7

3. For the product development, we were not familiar with the accessment standard, so there is lot of information contained in the report, but not easy for outsiders to find, so here we re-organized the structure and presented in a clear way (also see the new update on the pull-request)

**A.Dual Mining**
We provide mining tools that can give liquidity provider rewards with various tokens (WAX, BOX, and project team tokens). In this way, liquidity of trade pair will be easily boosted and this increases TVL level of WAX, thus improve its overall value of WAX chain.

Smart contract that execute dual mining
https://wax.bloks.io/account/lppool.box

**B. Swap Mining**
We provide mining tools that can give traders rewards when they swap (BOX tokens as default). In this way, trade volume is boosted and this increases activity level of WAX tokens.
https://wax.bloks.io/account/mine2.box

**C. Real-time Data Chart - Price line, liquidity trend and trade volume bar**
Defibox offers real time data chart for tokens. Users can easily see their token price, liquidity trend and trade volume in Defibox. This serves as a standard exchange center for WAX community.
![image](https://user-images.githubusercontent.com/93515916/173337219-870d7baa-1364-4587-ad3c-e702814b8e8b.png)

**D. Resource renting tools**
Defibox provides CPU resource rent service for WAX users easily stake/unstake their WAX for their resource. This resource tool gives WAX users a friendly experience when they encounter the resource requirement during the use of WAX.
![image](https://user-images.githubusercontent.com/93515916/173337265-e72196de-5a3d-4f3a-a893-3d7207141e27.png)

**E. API of Defibox asset**
Project team can get their token price API and token asset API from us. This price/asset feed can serve many purpose like price oracles, etc.
市场详情的API:
请求地址：https://wax.defibox.io/defibox/api/swap/getMarket
Method: post
请求的内容：
{
  "symbol": "string",
  "pairId": 0,
  "limit": 0,
  "type": "数值类型：1-自选，2-全部(默认)",
  "orderColumn": "排序字段：wax_balance-流动池，volume_wax-24h兑换量 total_yield_current-综合年化",
  "isAsc": true
}
Example：{
  "symbol": "",
  "pairId": 0,
  "limit": 10,
  "type": 2,
  "orderColumn": "wax_balance",
  "isAsc": true
}

About WAX community engagement, we will have several activities mixed, next time, we will presented by classifications

One last thing, about WAX strategic contribution points, I think Defibox belongs to "WAX strategic contribution infrastructure" where our DeFi platform provide basic service for buy, sell, add/reduce liquidity, etc. Besides Alcor, Defibox is the only exchange center that serves as an infrastructure.

Anyway, thank you for your feedback and we will continue to improve what we can to contribute more to WAX community

Kind regards

Raven Defibox

**Comment by rakeden** [comment]
Hi Defibox Team,

thanks for your feedback!
We've revisited your guild and we can't conclude the rating until all criteria to be established as a guild have been matched.
We'll schedule a call in the coming week to discuss your criteria. 

cheers,
OIG

**Comment by DefiboxTeam** [comment]
> Hi Defibox Team,
> 
> thanks for your feedback! We've revisited your guild and we can't conclude the rating until all criteria to be established as a guild have been matched. We'll schedule a call in the coming week to discuss your criteria.
> 
> cheers, OIG

Thanks for your feedback. Btw, about those items we added, is it possible to revise our points based on our items added? So that we can be more prepared for the next month. Thank you very much. Also looking forward to the meeting in the coming week. 

cheers,
Defibox
