### ISSUE TITLE
EOS Amsterdam July Appeal

### ISSUE THREAD

**Issue by yannickeosams** [wax-office-of-inspector-general/waxguilds#388]
Dear OIG,

In our last report (https://github.com/yannickeosams/waxguilds/blob/main/reports/amsterdamwax/2022-07.md) we mentioned helping the WAX team with the WCW and their infrastructure. Additionally we have been helping various prominent WAX games with their infrastructure through [binfra.one](https://binfra.one/). Lastly we are participating in various working groups focusing on scalability and collaboration between EOSIO chains. 

We've invested considerable amounts of time and money into this and feel these things provide a lot of value to the WAX ecosystem. Yet only the [binfra.one](https://binfra.one/) contributions are mentioned in the latest rating under commercial history solutions (with a 2/2 rating). We feel like it would have received more points if it was counted as a product or as individual engagements with each client. 

Also the lack of mention (and rating) of our contributions towards the WAX Cloud Wallet and these working groups felt unjustified. We hope you can take a second look at these contributions.

Lastly, we have received no points for testnet history even though we believe it has been online and available in the past period.

**Comment by rakeden** [comment]
Dear Yannick, 

regarding testnet history: We've had no choice other than to assume, that there was either configuration issues on your testnet node or the uptime hasn't been met to claim points for a testnet history. testnet history should have had ≥ 90% uptime between 21/06 and 15/07 to receive points.

Those are the sources we are using to evaluate:

**Showing availability after 01/07**
https://wax-test.validationcore.io/stats/guild/amsterdamwax?start=2022-06-21&end=2022-07-15
**Showing no availability at all**
https://oig.sentnl.io/guilds/amsterdamwax
**showing configuration errors on node before 01/07**
https://tools.ledgerwise.io/nodestatus/waxtestnet

Can you please provide us with a source to check that the availability has been given for the mentioned period? We will gladly add the point if you do so.

Meanwhile we are revisiting your other appeals and will come back to that with a separate feedback.

kind regards,

**Comment by kaefergeneral** [comment]
Hi Yiannick,

We revisited your submission and credited you a score for your contributions to the WCW.

As for binfra.one, note that currently points for commercial APIs are capped at 2 points. This would not change if you were to repott multiple engagements you are providing infrastrucutre to. This would just result in them being bundled as commercial history solutions.

As for your testnet history unfortuantely nothing is tracked on the OIG dashboard in that regard and if tools.ledgerwise.io is to believed there have been issues with your bp.json until the 27th of June. As we only credit points for infrastructrure that is properly announced int the bp.json and tracked, we can not credit you a score for it even if it was operationsa.

Best wishes,
your OIG
