### ISSUE TITLE
Token Gamer July Appeal

### ISSUE THREAD

**Issue by beasteh** [wax-office-of-inspector-general/waxguilds#389]
Hey guys,

Thanks for the time spent on the latest review. 3 appeal items for consideration:

1. It looks like both our YouTube and Twitch channels were omitted. High quality video production is extremely time-consuming but also offers immense long term value. We feel strongly that both of these products are point worthy, we've allocated significant resources to these areas. Both have growing view counts, many viewers are outside the WAX ecosystem and point omission is a strong indication that high quality, bespoke content regularly featuring WAX, is not valuable. These are unique offerings amongst WAX BPs and we need points allocated to continue confidence in our focus and commitment to these areas. We also don't believe that points have been bundled elsewhere (if they have, we feel that there's been a miscalculation). 

2. I (Boris) am not aware of another WAX mobile app that shows ALL NFT collections, WAX resources, tokens, WAX transaction feed, WAX drops and... **WAX transaction push notifications**. Push notifications in a native WAX mobile app is significantly superior to a telegram bot (which has it's own category!) and we noticed that there was no point increase after adding this incredibly useful and unique feature. The app is a high quality product, with thousands of users, we believe that more points are justified and kindly ask for this to to be reconsidered. 

3. We feel that the Mint One podcast is significantly undervalued, point-wise. Although not at the thousands of listeners, we know from feedback that prominent figures in the industry listen - stakeholders in the largest projects, game devs and influencers. The move to video has been a step-change in quality and is attracting industry attention. Again, this is a unique offering and we would like the single point allocated to kindly be reconsidered.

We appreciate the effort involve in evaluating products and guild offerings, it's an incredibly difficult task. We hope you agree that the products we have chosen to pursue are high risk / effort and resource intensive. From our perspective, it is discouraging to see more common / basic products such as CPU rental services receive more points when these do little to further WAX outside its own userbase.

Thank you,
TG Team

**Comment by kaefergeneral** [comment]
Hello TG Team,

1.) When evaluating contributions, especially content, we look at WAX specific content. When evaluating your Youtube & Twitch channel. As far as we can tell there was no WAX related content on your Youtube channel over the course of the last evaluation frame. While we do acknowledge, that it takes effort to produce high quality videos, we still have to evaluate them based on content and reach. 

2.) There seems to be a confusion on your end. Notifcations were introduced in your previous submission and resulted in a significant score increase. We are not sure though, how WAX Mobile App notifications are "significantly superior" to a telegram bot. As from our point of view both serve the same purpose and as long as they have the same functionality and are reliable, there is no real difference. Other than not being reliant on Telegram. Based on reliability we still slightly increased the score after some internal discussion.

3.) Unfortuantely we can not really take your mentions into consideration. We do value your contrtibutions, but based on the metrics we have, we do not see a point increase warranted at this stage. We will keep revisiting though.

As OIG we are focused on what benefits the chain the most. Sometimes this leads to short term needs being scored higher than what you would usually expect. Like it was the case with recent CPU rental services, that by now have dropped in score again, as demand for such services decreased. But you should also not underestimate the effort and ressources that go into services that seem basic. Especially as they not only serve the community, but developers alike.  While we appreciate the effort Guilds put into onboarding new users and projects, and make WAX known, chain and ecosystem stability are always a core focus.
But events and contributions that significantly impact the prominence and adoption of WAX will always be awarded as such.

Best wishes,
your OIG
