### ISSUE TITLE
bountyblok - July 2022 appeal

### ISSUE THREAD

**Issue by bountyblok** [wax-office-of-inspector-general/waxguilds#390]
Hi IGs,

1. Novopangea game went live but the score hasn't changed - last month's issue it was stated that you would revisit this once the game goes live: https://github.com/wax-office-of-inspector-general/waxguilds/issues/348

2. lazy integration with WAX wasn't considered - is this because it will be in the next report?

3. Contests have been quite popular we provided metrics - we can provide a lot more if needed - among dozens of projects on WAX, this tool has helped the WAX Team incredibly, and responsible for a LOT of the engagement during NFT NYC. They can 100% vouch for our 2 products on how helpful they have been to them: Contest + Distribution, so can you please revisit this score?

Thanks,
Dimitri

**Comment by kaefergeneral** [comment]
Hi Dimitri,

1. As no additional metrics were provided and the project scored points past the usual decay timeframe we scored based on the total trade volume, this granted a small point increase and prevented further decay.
We will revisit the score once more metrics are provided or impact increases.

2. We added an initial score for lazy.com. We have to monitor how the site evolves and if it starts to get traction in the broader NFT community outside of WAX so it gives us visibility.

3. Score has been revisited.

Best,
your IGs
