### ISSUE TITLE
EOSphere Guild - July 2022 Appeal

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#392]
Good-Day OIG,

Our WAX Technical How To content is currently being used to expand the wax-developer GitHub technical guides, this was confirmed with @rakeden yesterday.

We have previously been awarded points for this collaboration under the "Fulfilling Monthly Requirements" which wasn't used this last evaluation.

Can the OIG consider awarding similar points to our Guild perhaps under "Engagement - ecosystem-dev"

Thanks

**Comment by rakeden** [comment]
Dear Ross,

thanks for your appeal. After revisiting we considered the following change:

- We added 1 point for your contribution.
- We are decaying that category from last evaluation and will continue to do so, as we consider it part of your ecosystem contribution.
- We also want to encourage you to proactively add those articles to the developer.wax.io documentation and will consult you on how to do so

kind regards,
OIG
