### ISSUE TITLE
Defibox July Appeal

### ISSUE THREAD

**Issue by DefiboxTeam** [wax-office-of-inspector-general/waxguilds#393]
## BP Details

**Guild Name**
Defibox

**Guild Name**
https://wax.defibox.io/

**Guild Contact in Telegram**
@ravendefibox

**Technical Part**

1.“providing history solution”, we got no points and got feedback as “no public node”, but the actual is We have built a Hyperion node, and now the incremental node has become a full data node, currently in the process of synchronizing full data, please check the link below
https://wax.validationcore.io/validations/bp.box
![image](https://user-images.githubusercontent.com/93515916/181462741-00b0cd46-61f0-40b9-b7c4-e68d0a24b2bc.png)

2.We do have“Test history”but we did not get any points
Please check the links below
https://wax.defibox.io/waxtest.json
https://wax-test.validationcore.io/validations/bp.box
https://validate.eosnation.io/waxtest/producers/bp.box.html

**Product part**
We have the following product features, but we did not get any points from those.

1.Dual Mining
Smart contract that execute dual mining
https://wax.bloks.io/account/lppool.box

2.Real-time Data Chart - Price line, liquidity trend and trade volume bar
![image](https://user-images.githubusercontent.com/93515916/181462907-f57ac69a-8453-4887-a1f2-bfc662716106.png)

3.Resource renting tools
Defibox provides CPU resource rent service for WAX users easily stake/unstake their WAX for their resource.
![image](https://user-images.githubusercontent.com/93515916/181462984-9bf0ec13-769e-4a67-9939-aa639c5947c8.png)

**Community part**
We have the following part, but not credited as contribution to WAX community:
1.WAX Project Cooperation with Dual mining:
![image](https://user-images.githubusercontent.com/93515916/181463033-de32939b-b89e-4bca-a13b-7e910a7239f6.png)

2.WAX DeFi Episode on Youtube
![image](https://user-images.githubusercontent.com/93515916/181463126-7b6fa7c4-2427-47a1-8b67-493f844029be.png)

3.Donation to WAX Ecosystem as a DeFi contributor
With our protocol income from DeFi, we decided to contribute 40 WAX per day to WAX ecosystem account: netfeeac.wax

Summary: We made lots of efforts on those points, but it didn't get recognized as contribution. I was wondering if you guys can check them again and see if some of them can be judged as contribution and get points. 

Thank you for your feedback and looking forward to your reply.

**Comment by rakeden** [comment]
Dear Defibox team,

thanks for your appeal. See our following feedback please:

**Tech-OPs**
1. “providing history solution”
- Hyperion history needs to cover at least the last 4 weeks of data. [≥95% uptime full 2p, 95%→70% 1p], so in this case we are looking at the past 4 weeks.

2. We do have “Test history”
- We granted 1 point. Note: With guideline 4.4 we will be granting points for testnet v2 OR testnet dfuse ONLY.

**Product Defibox + Features**
- We are considering those tools as part of the product defibox and therefore grant no additional points for them.

3. Donation to WAX Ecosystem as a DeFi contributor
- This is mandatory for defibox to be scored as a product. But it's also factored into the score of defibox!

kind regards, 
OIG
