### ISSUE TITLE
Blacklusion July Appeal

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#394]
Hey IGs,

**History & Hyperion**
the notion document states for our history solution: "Issues with full history. Some times server is not reachable."

Comparing this to other guilds:
Taking the data until the Guild cutoff. We will take the validationcore.io data for this, as this is the only tool that offers a dateframe selection:
https://wax.validationcore.io/stats/guild?start=2022-06-15&end=2022-07-15

- Waxsweden - 96% v1 - 47% v2 - 3Points
- Sentnl - 98% v1 - 47% v2 - 3Points
- Liquidstudio - 95% v1 - 88% v2 - 2Points
- waxmadrid - 84% v1 - 86% v2 - 3Points
- blokcrafters - 92% v1 - 89% v2 - 3Points
- Dapplica - 17% v1 - 10% v2 - 0,5Points
- blacklusion - 81% v1 - 86% v2 - 0Points

Judging by these scores, I do not understand the following things:
1. why does Liquidstudio get 2 points and not 3 
2. How does dapplica score 0.5 points, if that was clearly stated in the past that this is not possible: https://github.com/wax-office-of-inspector-general/waxguilds/issues/307#issuecomment-1113078693
3. how can we score not a single point for our history solution. We have stated in the report that we had some abuse this month, as I have also written Rakeden on the 5. July (closely after constant abuse), so that the IGs are informed about this beforehand and we don't just claim anything once we submit the report. I do understand that abuse is no excuse. But even then, scoring us with 0points seems a bit odd in comparison. I am happy for every guild getting points for Hyperion, but the distribution seems a bit off.

**Wax Pager**
That month we finished the complete rewrite of our WAX pager bot that sends notifications about the validationcore status for guilds that sign up. Especially now that the scores are considered for evaluating guilds, it is more important for guilds to get notified about issues detected by us. That product isn't mentioned anywhere in the report, nor scoring points.

**Comment by kaefergeneral** [comment]
Hi Leonard,
thanks for the extensive people, we really appreciate the work.
There are some inconsistencies in the checks across validations and our own checks. 
This can sometimes also lead to inconsistencies in our ratings.
As for your score and the score of dapplica this seem to simply be errors and have now been adressed.

We also credited a score for WAX Pager as Community Tool.

Best wishes,
your IGs
