### ISSUE TITLE
CryptoLions Guild - September 2022 Appeal Part 1 

### ISSUE THREAD

**Issue by TarasCL** [wax-office-of-inspector-general/waxguilds#433]
I assume I can create several issues during one appeal process. I will create another issue later today.

1. We have testnet history. We would like to have 1/1 for this, but we still got 0/1. Probably this is a mistake.

2. We got 2/5 for kolobok.io game. We would like to have 4/5 because we worked hard to develop new features and invested $15k in August, taking into account that the game give us 0 profit.

**Comment by TarasCL** [comment]
Here is the updated appeal, sorry, I did not know I cant create several issues, so in order to not create another issue, I will add comments to this issue.

I will appeal with these key topics now:

1. Kolobok.io - metrics are not improved, but we ask for more points because we do hard efforts to improve this legendary one of the 1st top games in WAX. And I think it also received incorrectly low valuation for many previous months. We ask for +24 point here. 

2. SA - we got lover points comp to prev report. But metrics improved a lot compared to prev report. And also we actually improved the standart with this great tool https://simplebacked.cryptolions.io/ (more about this is below). So now anybody can back NFT with some FTs with help of this nice UI. Also we started ideation for SA 2.0. 
So we have 3 improvements, but got decreased points. We ask +18 points for SA. 

3. SimpleMarket.io - Metrics improved a lot, points not improved. Also, you probably not put enough attention to this beautiful and useful tool (in main menu of simplemarket press 'Create NFT' tools.simplemarket.io, this was reportrd but you maybe missed that). Any user can create NFTs and start selling, complately free and easy to use, also used by some games creators. 
We ask +24 points for this. 

4. Our full time team member dedicated to China market communications. He does a lot of promotion for WAX for years. This report period he worked even harder and we added 4 evidences of his work with links. And we think his work was valued incorrectly low points in many previous reports, ask you to compensate this in current report also. - +9 (ask +18) because of higher efforts and 4 evidences, and to compensate low points during last few ye- +9 (ask +18) because of higher efforts and 4 evidences, and to compensate low points during last few years.
Based on these 2 arguments we ask + 36 points for this. 

5. SimpleBacked - we forgot to report it, please consider this great new product, because this is our 1st appeal ever and we did not grasp that we cant add to the report during the appeal. Please make a new rule exclusion for 1st appeal, for everybody, not only for our guild. https://simplebacked.cryptolions.io/ we put hard efforts into this and forgot to mention in the report. As I described above, users can easily back their NFTs with FTs in this tool. We ask +36 points for this. 

6. Msig on wax testnet - this was reported, but you probably have not noticed, this is already on WAX testnet https://msig.app/waxTest 
 It is big step for WAX gamers guilds, so they can easily manage their funds and NFTs as a community (game guild, DAO etc). We ask +36 points for this. 

7. All the rest arguments: our guild has #1 reputation without any blames failed user expectations etc - so we contribute to WAX reputation, SA strategic impact and 1st big WAX contracts (GPK, Shatner, etc) which we still support, #1 voted guild for the last 8 months, frequently #1 top performans of infra. We ask to fit these into some category, we ask +60 points for these.

**Comment by TarasCL** [comment]
8. One more short comment about our WAX testnet histore. We have updated our wax-testnet.json at 29 July, so I wonder why it was not evaluated during prev tech evaluation (~10 Aug as I understand), we are still getting 0 points for it. We ask to give us 13 points for this to compensate that, if possible.

**Comment by kaefergeneral** [comment]
Hi Cryptolions,

please find our feedback below:

1. Unfortunately effort and money put into a project does not necessarily equate to value right away. Neither does past sucess. Unless metrics improve we don't feel it would be reasonable to increase the score of Kolobok. Given the invested effort we will halt the decay for now.

2. We reconsidered this, but couldn’t come the conclusion that SA is providing enough value to grant more points. It’s rarely used by new devs, mostly CL projects. Backing of NFTs with FTs is a nice feature but has proven to rarely being utilized.

3. The current metrics of simplemarket do not justify a score increase.

4. After revisiting the content, we could not identify a significant increase in relevance. Community engagement and support is evaluated based on continuous effort and contributions. A one time increase in releases or engagements does not directly translate to an increase in score.

5. Out of fairness to other guilds we can not accept new submissions or information that goes beyond clarifications after an evaluation cutoff has passed. Furthermore we consider this part of the SimpleAssets token standard and it would not contribute to individual points anyway.

6. We usually do not grant points for smaller tools until they are released on mainnet. As we like the tool we will make an exception in this case and grant 1 point for now. We will revisit the score once the tool is released on mainnet and proves usage.

7. First of, strategic points are NEVER granted upon request. Furthermore the guidelines are pretty clear on this.
"Strategic points are only awarded for Products or Engagements that already score the maximum points in their respective category."
Evaluations are always based on the current evaluation timeframe and scores that carry over from the previous evaluations.
Please understand that we never grant or increase points for past efforts or contributions outside of this scope.

8. We credited you points for your testnet history. You do have an issue with missing blocks we would request you to handle.

For the next report, please stick to the general rules in the respository: reports/cryptolions1/Guild report Aug , 2022 is not a valid flename and doesn’t follow any your previously used conventions.

We understand that this is your first appeal, as a general rule we would ask you to refrain from asking for points. The point of the appeal is to note issues or clarify things that were unclear.
You can ask us to revisit something if you think it was severely misjudged or has been overlooked. But we will never take point requests into our consideration.

sincerely,
your OIG
