### ISSUE TITLE
Dapplica September Appeal

### ISSUE THREAD

**Issue by dapplicaio** [wax-office-of-inspector-general/waxguilds#436]
Hello, I would like to know why we got 3 points in "Providing history solutions (e.g. V1, V2, dfuse, etc...). (0 to 3)" in Tech review in August and now it says 2 points. 

As we provide all history

**Comment by rakeden** [comment]
Hi Dapplica,

we corrected the points to full points for your full v2 history solution!

cheers,
OIG
