### ISSUE TITLE
Token Gamer September Appeal

### ISSUE THREAD

**Issue by TokenGamerRob** [wax-office-of-inspector-general/waxguilds#437]
# TokenGamer Appeal August 2022 

As always, thank you for reviewing our report, infrastructure, and services.

We agree with the majority of the point awards for this round but we are very surprised that the Discord server received no points for ecosystem development. 

Since the report was submitted our userbase has doubled to near 200 users, It's active in almost every channel and continues to grow in users and usage daily.

We strongly believe this is a great way to bring infrastructure providers, developers and users of the Wax Blockhain together be able to manage, develop and participate in new and exciting things for the Wax ecosystem. This has been a lot of work to get going but we truly believe it will be beneficial for the WAX community, the OIGs, and the BPs long-term.

We'd also like to draw your attention to our podcast, YouTube channel, and Twitch. We put a lot of time into maintaining these 3, each is experiencing strong growth, and we ensure WAX is focused on regularly. Our content is high-quality and extremely consistent and we still feel it's a little undervalued in our scores.

Additionally, as a side note, can you please update the dev.waxaccount.com note for product 2 to https://waxaccount.com its production URL.

**Comment by kaefergeneral** [comment]
Hi TokenGamer,
we are monitoring the Discord but at this stage we do not consider it point worthy yet, as there is only a hand full of active members across all channels. We do hope this will change as the userbase grows.

Unfortuntely youtube, twitch and podcast do not have a high enough relevance right now given their content and metrics.

We did though, credit you points for the Gamescom presence.

Sincerly,
yous OIG
