### ISSUE TITLE
WeCan October 2022 - late appeal

### ISSUE THREAD

**Issue by We-Can-dev** [wax-office-of-inspector-general/waxguilds#478]
Dear OIGs,

Probably this isn't the best use of special appeal window, but i have to use it due to not being able to properly review and address the report during the usual window. Hopefully there will be no other circumstances like this in the future.

I want to ask you to reinstate our 0.5 points which we received last month in the field 
"Providing useful APIs (0 to 2)" for our IPFS (https://ipfs.wecan.dev/ipfs/) gateway that we still provide and will be providing and supporting:
https://ipfs.wecan.dev/ipfs/QmcXzGedyu3AK5rVsppfJsYJ5F2F9b8etQ8wKmSEtfGXd4
https://ipfs.wecan.dev/ipfs/QmceMuwiWLPr3aeY8TJwB8KAjHwMiEhux2nVgC5gvLaZFc
https://ipfs.wecan.dev/ipfs/QmUmRfTc2XWnDtCmq1zhx64bKFjYmk8HMSjqoqH2scpSbv
https://ipfs.wecan.dev/ipfs/QmVYuxagtqAe58bkvSWWLwA5K6kCScbhduf9mmvSxck2Hb

https://status.wecan.dev/790677499 (100% uptime)

It's mentioned in our [bp.json](https://wecan.dev/bp.json), but i guess the new format allows to put it into a separate category for IPFSs for better discovery and we'll do it asap as we figure out with other monitoring entities how to avoid fail positives - because only ledgerwise reads them properly for now.
I guess it's because i forgot to mention it in this month's report, so it fell out of the context in the appeal review as well.

Thank you!

**Comment by kaefergeneral** [comment]
Hey guys,
sorry for the late reply.
This appeal was fine. It was one of the things the special appeal is for.
Not granting you the points for IPFS was an obvious oversight, so we updated it.

Thanks for reaching out.
