### ISSUE TITLE
RATING APPEAL EOS Arabia - Dec 2022

### ISSUE THREAD

**Issue by EOS-Arabia** [wax-office-of-inspector-general/waxguilds#512]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. only 6% uptime for testnet Hyperion API:
seems like there is an issue with validationcore.io related to our testnet node
we didn't change anything pertaining to our testnet node except the upgrading to Hyperion version 3.3.7  which was done without any downtime.
https://drive.google.com/file/d/1Nui0OUkZsKivD7iQ8Skk0QW8dTLn-E9X/view?usp=sharing

You can see we have only two failed APIs related to History and this thing is not new, we have had it from the beginning of launching our Hyperion node on testnet.

We wonder if we didn't change anything and we just have 2 failed checks why did we only earn 6% from 1-10-2022 until 11-10-2022
the logic should say we have all things correct"like the previous month" except two APIs are not so we should lose 6% for example not earning only 6%.
https://wax-test.validationcore.io/stats/guild/eosarabianet?start=2022-11-01&end=2022-12-11
in the previous month"November " we got the full points for testnet API, in this month we only earn 6% after only the upgrading process for Hyperion.
Also you can check the https://tools.ledgerwise.io/ and  https://oig.sentnl.io/

2. we get 0 points for AA API in the useful API section.
https://wax.validationcore.io/stats/guild/eosarabianet?start=2022-11-01&end=2022-12-11

Thank you

**Comment by kaefergeneral** [comment]
Hi EOS Arabia,
we adjusted the score for providing Atomic Asset APIs. It seems this was a hiccup with notion.
As for the testnet hyperion, we only grant points for full nodes with good uptime.
Your endpoint had not only tracked issues on both https://oig.sentnl.io/ and https://wax.validationcore.io. But also, even to this date, it is failing manual checks. 

Best wishes,
your OIG
