### ISSUE TITLE
RATING APPEAL - eosauthority Dec 2022

### ISSUE THREAD

**Issue by eosauthority** [wax-office-of-inspector-general/waxguilds#514]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

No points for the AA API for some reason in Dec 2022. All previous months were correct
Please see AA API stats https://wax.validationcore.io/stats/guild/eosauthority and AA API endpoint https://aa-api-wax.eosauthority.com/health

Thank you

**Comment by kaefergeneral** [comment]
Updated.
