### ISSUE TITLE
WaxMadrid January 2023 Appeal

### ISSUE THREAD

**Issue by EosioMadrid** [wax-office-of-inspector-general/waxguilds#549]
Hi IGs,

first of all, thank you for the review.

I'd like to appeal to recheck the score (and penalty) regarding the publishing feed data via the delphi oracle service.

On my end, I cannot see anything wrong on the service for the last weeks.

Thanks again for your work.

**Comment by kaefergeneral** [comment]
Thanks, we are not entirely sure what happened here. 
Granted the points and removed the penalty.
Thanks for the heads-up!
