### ISSUE TITLE
RATING APPEAL LEDGERWISE

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#550]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. History Testnet - We are providing Hyperion which shows 0% availability on the Validation core and is false. Our Hyperion servicers are healthy and were up. Though we don't have data to back this and now we understood why 3-4 resources are required to check the health of Guilds. 

Will it be possible for IGs to do a manual check on availability? 

2. Tools.ledgerwise.io - We feel tools shouldn't be decayed this time as we put our resources to develop both [grafana](https://grafana.ledgerwise.io/) and adding a few changes to the dashboard including Oks bpjson chain json check. We also waited for more suggestions from IGs. 

We will be rebuilding the tools to make it better for IGs to use, with a table and scores input for different criteria. It might take a little time though. 

Thank you

**Comment by leonardofficial** [comment]
Hi tanish, Leonard from blacklusion here. Just to give some insights on your testnet Hyperion. We can verify that **yes**, indeed your Hyperion was up during the past evaluation period. However, the feature "transfer_memo" was disabled. The score of the validationcore is not false, as we (until now, but might change in the future) required this to be enabled to pass validation. The endpoint is counted as down if at least one check is not passing (which is the case here). Hence the validationcore score is working exactly as intended.

There have been some discussions on disabling the check for transfer_memos entirely and I will leave it up to the IGs, if they even require this to be enabled. But there is always the option to reach out to us via telegram if you feel your guild is validated wrongly by us, so we can make sure your guild is validated correctly and fairly :)

**Comment by kaefergeneral** [comment]
Hi Tanish, 
I see Leanoard already gave you the feedback in regard to the "index_transfer_memo".
28th of December to 6th of January validation core and ledgerwise both are reporting 'issues'. Validation core is reporting 'Service Unavailable', and your own tool is not tracking anything at all. Based on this, we have to assume there was no availability as no uptime without errors was checked. As such, we can not grant the points for 95% availability.

As for tools.ledgerwise.io we had a decay set but removed it for now and reinstated the points.

Keep up the good work.
