### ISSUE TITLE
BP APPLICATION

### ISSUE THREAD

**Issue by brunoocaranza** [wax-office-of-inspector-general/waxguilds#551]
## BP Details

**Guild Name**
Your guilds name

**Guild Name**
https://example.com/

**Guild Contact**
example@example.com

**chain.json location**
https://wax.example.com/wax.json

**Guild Jurisdiction**
Location

**Node Jurisdiction**
Location

## Application Requirements

* [ ]  No guild member can be an active IG, unless a replacement for his||her seat has already been elected.
* [ ]  Public website available.
* [ ]  Make an intro blog post.
* [ ]  Guild account registered as a producer and voted in on WAX Testnet for seven days before submission deadline. Previously registered guilds that unregister will have the seven day timer reset if they are unregistered for 24 hours or longer.
* [ ]  Make a request to the IGs to be voted in on testnet.
* [ ]  Interviewed by the inspector general committee.
* [ ]  Joined WAX Guilds Keybase team.
* [ ]  Added emergency contact information to Guild roster (available in Keybase).

## BP Questionaire

**Please provide some information regarding when and how your Guild got involved with the EOSIO or WAX ecosystem. Links to resources are helpful.**

Your Answer

**Has anyone in the Guild previously produced blocks on an EOSIO or DPOS network in the past? If so, which ones and what nodes did they help operate?**

Your Answer

**Please provide information regarding projects that your Guild is working on to improve the WAX ecosystem. Information about plans, progress, and timelines is helpful.**

Your Answer

**Please share any usage metrics you have, if any. This includes data specific to applications and user activity driven to the WAX ecosystem as a result of your Guild's efforts.**

Your Answer

**If possible, please share information about businesses that your Guild is engaging with that are seeking to learn about and leverage the WAX ecosystem in some way.**

Your Answer

**Please share any information regarding community building efforts championed by your Guild. This can be facilitating translation of documentation, organizing meetups, and otherwise driving social and human engagement within the platform.**

Your Answer

**Do you have any feedback for improving the Office of Inspector General, the Inspector General Guidelines, or this form?**

Your Answer

**Comment by brunoocaranza** [comment]
> ## BP Details
> **Guild Name** Your guilds name
> 
> **Guild Name** https://example.com/
> 
> **Guild Contact** [example@example.com](mailto:example@example.com)
> 
> **chain.json location** https://wax.example.com/wax.json
> 
> **Guild Jurisdiction** Location
> 
> **Node Jurisdiction** Location
> 
> ## Application Requirements
> * [ ]   No guild member can be an active IG, unless a replacement for his||her seat has already been elected.
> * [ ]   Public website available.
> * [ ]   Make an intro blog post.
> * [ ]   Guild account registered as a producer and voted in on WAX Testnet for seven days before submission deadline. Previously registered guilds that unregister will have the seven day timer reset if they are unregistered for 24 hours or longer.
> * [ ]   Make a request to the IGs to be voted in on testnet.
> * [ ]   Interviewed by the inspector general committee.
> * [ ]   Joined WAX Guilds Keybase team.
> * [ ]   Added emergency contact information to Guild roster (available in Keybase).
> 
> ## BP Questionaire
> **Please provide some information regarding when and how your Guild got involved with the EOSIO or WAX ecosystem. Links to resources are helpful.**
> 
> Your Answer
> 
> **Has anyone in the Guild previously produced blocks on an EOSIO or DPOS network in the past? If so, which ones and what nodes did they help operate?**
> 
> Your Answer
> 
> **Please provide information regarding projects that your Guild is working on to improve the WAX ecosystem. Information about plans, progress, and timelines is helpful.**
> 
> Your Answer
> 
> **Please share any usage metrics you have, if any. This includes data specific to applications and user activity driven to the WAX ecosystem as a result of your Guild's efforts.**
> 
> Your Answer
> 
> **If possible, please share information about businesses that your Guild is engaging with that are seeking to learn about and leverage the WAX ecosystem in some way.**
> 
> Your Answer
> 
> **Please share any information regarding community building efforts championed by your Guild. This can be facilitating translation of documentation, organizing meetups, and otherwise driving social and human engagement within the platform.**
> 
> Your Answer
> 
> **Do you have any feedback for improving the Office of Inspector General, the Inspector General Guidelines, or this form?**
> 
> Your Answer

**Comment by rakeden** [comment]
closed, because incomplete
