### ISSUE TITLE
RATING APPEAL  - EOSphere v4.8 March 2023

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#585]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Product 1 - Our HeadsUp platform is a constantly being developed on with features regularly being added. In previous months we have been awarded 4 points, however this month we were awarded 3.5. Would you mind looking into this point downgrade?
2. History aaS - Previously we have been awarded 1 point for our commercial services, but this month we haven't received any. Would you mind looking into this pint downgrade.

Thank you

**Comment by kaefergeneral** [comment]
Hello Ross,

1.) Products regularly receive a higher score on public releases and are marked for decay with a target score later on, which is re-evaluated with every product update submission. We are happy to take your previous offer to have a call and get a run-down of the platform.

2.) One point was mistakenly deducted for your History aaS services. We have now granted you the missing point.

Best,
your OIG
