### ISSUE TITLE
RATING APPEAL - Dapplica

### ISSUE THREAD

**Issue by dapplicaio** [wax-office-of-inspector-general/waxguilds#586]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. DiyFarm is not in our product sheet, but it was reported 
3. RTP project (Product in development),  was sent to ig@wax.io with details on how to test it and again not rated anyhow, nor replied via email. 

Thank you

**Comment by kaefergeneral** [comment]
Hello dapplica,

1.) We didn't have any previous mention of DiyFarm, we don't have metrics and the website provided, aside of one concluded pool, is empty. So we didn't really have anything to score here.

2.) If you want to receive points for a new product in development, this requires a product introduction call and a targeted release date/roadmap. As this wasn't requested, the product was not scored yet. As you submitted it confidentially, we assumed you preferred not to have it added to the product sheet.

Best,
yout OIG
