### ISSUE TITLE
RATING APPEAL - Blacklusion March

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#587]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. **Prometheus Exporters** - Prometheus Exporters are used by other guilds as well. Not just by us. This month we didn't receive any points for it anymore. There was also no mention of decaying points in previous reports. Was this just overseen, or did you decide to not give us points on this product? If so I would love to know what we can do, as we are committed to maintaining this product.
3. **Blacklusion Pager** - This month we also didn't receive any points on our bot sending push notifications about the validation status of guilds. It is working fine. There is just one minor bug where notifications are sent twice, that's why we've only added a couple of guilds that were asking for it. Once that is resolved we will also advertise it more publicly, but as of now it is already working and helping multiple guilds. This is definitely a product for which we would like to receive points, as with the frequent discussions about the validation status, we can see how this will provide a lot of value, informing guilds immediately about a misfunctioning and hopefully minimizing the instances.

Thank you for your work and for looking into this issue

As a bonus I would also like to mention, that I would love to see a calendar subscription for all IGs dates (guild cut off, appeal starts etc.), maybe even with a monthly guild call inside. This will take about 10mins to setup for one of you, and should help essentially all guilds to keep track of the dates and get them more engaged together. Thank you!

**Comment by kaefergeneral** [comment]
Hello Leonard,

1.) This has been corrected.
2.) The Blacklusion Pager has not been getting any individual points since the 4.4 evaluation in September and we considered it an extension of validationcore. Once you start advertising it and submit us metrics, we will reconsider granting individual points for it.

We plan to discuss hosting a calendar of sorts.

Best,
your OIG
