### ISSUE TITLE
Wizards Guild March 2023 RATING APPEAL

### ISSUE THREAD

**Issue by BigMike690** [wax-office-of-inspector-general/waxguilds#588]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. History Rating - 

We were upgrading in hence to antelope between Feb and March, around Jan our primary ship crashed and had to be recovered.

Mainnet hyperion downtime with HTTP 503 returned across all monitors, since end of january. Testnet APIs have no CORS configured, which makes the APIs unusable for wallets and clients

This one has been resolved since Feb 18 and cors was also fixed.

Thank you,

Big Mike
Wizards's Guild Representative

**Comment by kaefergeneral** [comment]
Hi Mike,
The comment that said 'since end of January' was from the last technical evaluation, we are aware it has been fixed in the meantime. We removed it now, as it is resolved.

The comment has no impact on the rating and was just set as a notification.

Best,
your OIG
