### ISSUE TITLE
Antelope ^v3.1 readiness state - 27th march upgrade

### ISSUE THREAD

**Issue by rakeden** [wax-office-of-inspector-general/waxguilds#589]
Dear guilds,

this is the current state of upgrade readiness for network upgrade to ^v3.1, planned to roll out march 27th.
**Please update your readiness state through commenting to this issue if you are not ready yet**

GUILD | READY | VERSION
-- | -- | --
3dkrenderwax | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/567/files#diff-bdcf6f948027aa19a80e4fe445007ef97a2918012794148dbe52985ede82613cR7) |	v3.1
alohaeosprod | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/578/files#diff-accc75f77624bd4e2280f3af4f16f1a9aea6cc673bd937a6ae66fe7a962f13c3R6) |	v3.1.4
amsterdamwax   | ✓✓  | v3.1.x
blacklusionx | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/575/files#diff-4fbedbfd032d580032d637bf000e1136b6e838409b270393f0b5b06107abf9bcR9) |	v3.1.0 - v3.1.2
blokcrafters | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/582/files#diff-0fd87253c3b0f2e567a5b384472d80a3b651ca78357ba0bf9f94523bf13ebd38R8) |	v3.2.0wax01
bountyblokbp |  [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/569/files#diff-842986e6a93ed244422b5ce63437213bbd1c3f663f461042ad093445f94a451bR5)  | 	v3.1.x
bp.box | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/562/files#diff-e9a8b70a2c43d2f6c7aa5dc59ef441e646610cdf8038cb5dc4d7a753c43dce24R13) |	v3.2.0wax01
cryptolions1 | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/560/files#diff-31c5691a35231995deea658613b898d8554e0c66d754f30c1ea092cb07308d5eR13) |	v3.1
dapplica | [```✗✗```](https://github.com/wax-office-of-inspector-general/waxguilds/pull/571/files#diff-064c322eb47f707282360aec0af08f2c7c4bc1d549dc66799fb180e49450957dR7) - 9th march | 	v3.1
eosarabianet | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/563/files#diff-5dd22cc096152a6c9597414c8efc6f8a709262037908daf5381badda92f99f4cR7) |	v3.1.* - 3.2.*
eosauthority | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/558/files#diff-c5f03c28d6773e112279b4b6d798a46c68993db04e443658b2a48676f83a5734R7) |	v3.1
eosdacserver | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/564/files#diff-1f4e14751cc54d72e2db7f442325136be1430bb0413c199f534e2c724e37b142R6) |	v3.1
eosiodetroit | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/580/files#diff-30fb171a0c41c81e44d198ac0d902ed19e96c069167b5903313b1c3e3f9d2acbR16) |	v3.1.0 - v3.1.2
eosphereiobp | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/554/files#diff-ea29b2c9486ed00ce382054ba488ccf4be09b6b92e87d885fb5936956773574aR14) |	v3.2.x wax01
eosriobrazil | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/555/files#diff-f270ea6014c0878a6dd5952f00a4af7c1c24ad0100651f5134d89bc15175fd5cR7) |	v3.1
greeneosiobp | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/570/files#diff-db2df76bcace02187e3b14433a1c263a5b25ec294c1bdc418454d37d61420d6fR16) |	v3.1.2wax01
guild.nefty | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/520/files#diff-6f5ba0638e4624883a610dbb8bdf114312de07c65d4f459ebcce2a1f2247a99cR20) |	v3.2.0wax01
guild.taco | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/572/files#diff-3710f29526542763ca35256f8f96d68393dd2cfb4d175410db98b7c04fac692eR29) |	v3.1.4
ivote4waxusa | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/568/files#diff-54a52199b444b1fe3db9ec2cfca1c18bb869706d1c251f3e1c416c7e14782ebcR15) |	v3.1.x
ledgerwiseio | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/565/files#diff-055af333270839685a62b093f989cb8378938eea68b36fa72a56b8b7b87fdf9aR6) |	v3.1.4
liquidstudio | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/583/files#diff-e51e37981d4d7b11d7bb5f032595bddac73707a67f9ce1a4dba41f733cfa7d0bR7) |	“latest”
nation.wax | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/576/files#diff-a02f5ef0bab419a0f8b0283d9f6007e1c4fa8595adfe50525fb5750eba12dcddR9) |	v3.1
oneinacilian | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/557/files#diff-162ebbfb1b09d91cb77df377b3cf466342045f9b22388e50329a9efe8fe79de1R8)  | 3.1.3wax01.
pink.gg  | ```✓✓``` | v3.1.3wax01
sentnlagents | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/553/files#diff-65f83a0b6144c97ab0a44fae9c99b0e1bf0293f0d5f75ceb9b66d11e2cd94a88R7) |	v3.1.3
teamgreymass | [```✓✓```](https://github.com/wax-office-of-inspector-general/waxguilds/pull/561/files#diff-35a9ea48da1e04f645ccdbbdc0f62d5b41a2d55e5b016104db76a0bac0fefbd4R7) | 	v3.1.x
tokengamerio | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/579/files#diff-387dcfb0d116b18237eb346d4239ac832093d1a574d752e37b13e1fa0ffb55c6R6)  |  	v3.1.3wax01
wax.eastern | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/566/files#diff-ee0f67d8eca654fb2fbdca47eb74da52ceb64ab7f4bb769681c0eb6d5b409751R8) |	v3.x
waxhiveguild | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/574/files#diff-59b8aabe92dd5262bcd90cad3dba9b542e4c3ae5a5dd277a4b4c8305d3f9afbaR7) |	v3.1.x
waxmadrid111 | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/559/files#diff-cf1650249ee5d4cb88f15b0c86d19dd2fe222ae64cc73305f9f35361f7a0fe5bR16) |	v3.1.3wax01
waxswedenorg | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/573/files#diff-a4d80a609b7268f9c2d55bb2783600a5128814b2ea58242bb5817aefa1606af4R6) |	?
wecandev | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/577/files#diff-3812236b5c881654e75cf319872b2b3ecfe97a4e991cd6d6dac009f69b9dc025R13) |	3.1.4wax02
wizardsguild | [✓✓](https://github.com/wax-office-of-inspector-general/waxguilds/pull/581/files#diff-7bb8834a95de68e927d9d1f9a5794dafd58ca5e8c1790956f1c95c94cb652785R7) |	3.1.4+

Not actively producing
GUILD | READY | VERSION
-- | -- | --
eosdublinwow | ✓✓  |	v3.1.4

**Comment by oneinacillian** [comment]
Hello, oneinacilian will have all upgrades to V3.1.X completed by March 19th at the latest.

**Comment by aaroncox** [comment]
Greymass is ready on all fronts.

**Comment by rakeden** [comment]
tokengamer is up-to-date

**Comment by oneinacillian** [comment]
> Hello, oneinacilian will have all upgrades to V3.1.X completed by March 19th at the latest.

Just to confirm that all oneinacilian nodes are now running 3.1.3wax01.

**Comment by mcicu** [comment]
eosdublinwow is ready, running `3.1.4` for bp and private ship, and `3.2.1` for api/p2p

**Comment by mcicu** [comment]
@rakeden I'm not sure why you put eosdublinwow in "not actively producing" section, care to detail?;
I've just updated the bp to 3.2.1, let me know if this qualifies us to be on "actively producing" list;

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/5434980/227764348-8e6d42ed-37dc-4139-8641-d4643f83b58a.png">
