### ISSUE TITLE
RATING APPEAL - EOSphere v4.9 April 2023

### ISSUE THREAD

**Issue by Rossco99** [wax-office-of-inspector-general/waxguilds#627]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Product Development - Our HeadsUp platform that is under continuous development with features added monthly continues to decay. As per our IG call 2 weeks ago we have reintroduced the platform to the WAX Guilds with a demo and walkthrough video that appears to have been well received https://youtu.be/3opNd_gS4Kg . We are certain of the value it brings to the network and ask for you to reconsider the decay score considering we are continually improving the platform. 

 

Thank you

**Comment by rakeden** [comment]
Hi Ross,

We agree that HeadsUp is adding value to the network.

As laid out last month, you were granted a bonus score with your public release in December that, from the start, was marked for decay with a target of three. We executed the reduction as planned, with currently no further deductions planned.

Best,
your OIG
