### ISSUE TITLE
Wax Galaxy (greeneosiobp) appeal - August evaluation 

### ISSUE THREAD

**Issue by sukeshtedla** [wax-office-of-inspector-general/waxguilds#65]
Hi Guys, Thanks for the evaluation.

We would like to submit an appeal on two points in our evaluation:

We submitted our monthly community report at the top of our monthly updates report satisfying the criteria for "Fulfilling monthly requirements" but we weren't awarded any points for the same. - In our monthly report we are also covering a specific topic every month. Last month it was WAX Governance and this time it was about WAX Defi.

We ran a lot of giveaway and social media campaigns in comparison to other guilds but are not awarded any points for the same. At least achieving 0.5 points would recognize the work we put into them.

**Comment by kaefergeneral** [comment]
Thanks, the points for your community update have now been credited.

We want to emphasize that there is no category for giveaways, nor did we see a coherent marketing campaign that warranted points in the category "Running Marketing Campaigns and Hosting Events".

Some of your activities on social media contributed to your scores in "Creation of [...] content" and "awareness building".
