### ISSUE TITLE
Aloha EOS - OIG August 2021 Report Appeal

### ISSUE THREAD

**Issue by artcorvelay** [wax-office-of-inspector-general/waxguilds#66]
Hello, under the Ecosystem Development Sheet the description for "Funko" shows "Decaying until launch" but we already launched TMNT series 1 several weeks ago. Can you please update this status and review the score accordingly?

Sincerely,

Aloha EOS

**Comment by kaefergeneral** [comment]
The note was missed to be removed, but the points were not actually reduced.
We removed the note, the points on Funko were not changed as they already reflected the correct value.
