### ISSUE TITLE
EOS Nation - OIG August 2021 Report Appeal

### ISSUE THREAD

**Issue by chillsauce** [wax-office-of-inspector-general/waxguilds#67]
### WAX Detective
Please consider awarding some points for WAX Detective. [WAX Detective](https://waxdetective.io/network) makes it easy to visually explore relationships between accounts based on their token transfer history and is being actively used on WAX to do things like investigate wash trading of NFTs or having fun with [visualizing the explosion of activity from the Binance exchange account](https://eosnation.io/eos-hot-sauce-116/#3). 

We did not have any development updates in this month's report, but we did have 1.7K users in August. 
<img width="1260" alt="Screen Shot 2021-08-29 at 6 03 37 PM" src="https://user-images.githubusercontent.com/37008057/131266773-75741ef7-07c6-4584-ac2e-7b74dea938ce.png">

### Ocean Defenders
Please consider awarding some points for Ocean Defenders. Initiated by a committed group of artists, scientists and watersport professionals, [The Ocean Defenders WAX NFT series](https://theoceandefenders.com/) aims to raise awareness about marine conservation, cooperate with sustainable businesses, and to educate in a fun way. EOS Nation & .gems have been hired to facilitate the blockchain deployment of this NFT series on WAX.

### Guild Update Social Post
Please consider awarding some points for publishing our Guild Update on social media and promoting it before the cutoff date. We published our Monthly WAX Report and shared it with our more than 12K Twitter followers ahead of the deadline. [See Tweet](https://twitter.com/EOS_Nation/status/1429574288638713863?s=20)

### Community Tools
Please consider awarding an additional point for building and supporting community tools. [WAX Name Service](https://waxnameservice.io) makes it easy to buy and sell premium WAX account names [(see sales data on chain)](https://wax.bloks.io/account/names?loadContract=true&tab=Tables&account=names&scope=names&limit=100&table=suffixes), and our [blocktivity smart contract](https://github.com/EOS-Nation/blocktivity-eosio-stats) tracks operations on WAX and feeds that data to explorers like https://blocktivity.info. WAX is currently ranked number 1 on blocktivity.

**Comment by kaefergeneral** [comment]
We added WAX Detective to your roster of Community tools together with the WAX Nameservice and increased the points in that category.

The submitted update lacked enough information on "Ocean Defenders" to warrant points being credited at this point.
With the uncertainty especially in the ecosystem development category, we usually refrain from attributing scores before a launch date is set, or in most cases, has actually taken place.

In regards to your Guild Update Social post. The requirement was:
"The update is supposed to be well written and directed at the community, not simply a copy of the git submission."
As your update happens to be a more or less exact copy of the monthly update you submitted you were not credited points.
As there was some inconsistency in rating this criteria, and uncertainty among guilds, we decided to credit points to everyone that submitted a post, until we released clearer remarks on our expectations on said posts.
