### ISSUE TITLE
RATING APPEAL - WeCan technical score

### ISSUE THREAD

**Issue by We-Can-dev** [wax-office-of-inspector-general/waxguilds#678]
Good Day IG's

We are providing public WAX Light-API as part of our expanded tech stack:
https://light-api-wax-main.wecan.dev/api/status
https://light-api-wax-main.wecan.dev/api/sync/wax
https://light-api-wax-main.wecan.dev/api/topstake/wax/1000
etc.
We're not sure about the contents of bp.json, but ended up breaking one validator which can't recognize this type of api https://wecan.dev/wax.json https://validate.eosnation.io/wax/producers/bp.wecan.html
Though, we have our public status page for the reference https://status.wecan.dev/794407553

Can you please review our points for the "Useful APIs" we were awarded with and add our Light-API to the list of accounted useful apis in addition to our AA API and IPFS?

Kind regards,
WeCan dev team

**Comment by blocksbarcelona** [comment]
Good morning Wecan team. Thank you for the heads up. We have added the lightapi score to your evaluation.
Regards,

**Comment by blocksbarcelona** [comment]
We got an internal discussion about your issue and unfortunately we have to remove the points and go back to the initial evaluation. Light API requires metrics submitted in the report in order to be evaluated. Please submit the usage metrics in the next evaluation. Thank you.

**Comment by blocksbarcelona** [comment]
Score updated.
