### ISSUE TITLE
Hive BP - August 2021 Appeal

### ISSUE THREAD

**Issue by hiveben** [wax-office-of-inspector-general/waxguilds#68]
Hi guys,

I have 3 issues I would like to appeal:

- Our second product was not rated and not put into the product sheet. Please check again. Progress can be reviewed through the link provided in the report.
- Ecosystem development was still not rated, despite continuous efforts to help projects, eg running their ads for free, providing snapshots, helping them with technical issues, as well as building products for them. If the products are not rated before release,  I understand, but there are other guilds which do get points for ecosystem support. 
- The article on how to buy WAX was not rated. It was specifically written for Funko collectors, who had trouble buying WAX. I compared several exchanges and selected Bittrex because it accessible to Americans and allows Credit Card buying. I understand though, if one piece is not enough to get points, but please make sure it was not overlooked.

Thank you!

**Comment by kaefergeneral** [comment]
There was some open conversation on scoring your second product. This has now concluded and points have been added.

The submitted information under ecosystem development were not extensive nor specific enough to warrant points.

Points for your article have now been credited under content creation.
