### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by mdcryptonfts** [wax-office-of-inspector-general/waxguilds#680]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. IPFS node - Didn't receive any points for ipfs.waxdaobp.io even though it is public and in our json (on and off chain)

Thank you

**Comment by kaefergeneral** [comment]
Unfortunately we are past the deadline for appeals.
But the issue has already been resolved prior to your appeal so it does not matter this time. Make sure to submit appeals within the designated timeframes going forward. :)
