### ISSUE TITLE
Blokcrafters BP - August Appeal

### ISSUE THREAD

**Issue by bdizzle32** [wax-office-of-inspector-general/waxguilds#69]
Hey IGs, we have 1 issue we would like to appeal:  Ecosystem development. - We published our month in review  https://blokcrafters21.medium.com/wax-guild-blokcrafters-month-in-review-94df9813a0a3 and also shared it via our social media. https://twitter.com/blokcrafters/status/1428451214669320195 please consider rewarding points for this.   Thank you!

**Comment by kaefergeneral** [comment]
Points were adjusted accordingly.
