### ISSUE TITLE
Blokcrafters appeal - August Evaluation

### ISSUE THREAD

**Issue by nickeles7** [wax-office-of-inspector-general/waxguilds#70]
Forgot to add this into our other appeal, 
appealing community engagement : hosting events/marketing

please consider giving us points for hosting events: 

Interview M.O.R.B.S project https://www.youtube.com/watch?v=fPRyfptJuFs&t=10s
Interview GNO City project https://www.youtube.com/watch?v=ZI-rUuzGnG0&t=6s
Interview Gods & Legends project https://www.youtube.com/watch?v=awMHV5mqis8&t=7s

**Comment by kaefergeneral** [comment]
Interviews are considered content, and as such contribute to your score in content creation.
