### ISSUE TITLE
RATING APPEAL (3DK Render)

### ISSUE THREAD

**Issue by 3dkrender** [wax-office-of-inspector-general/waxguilds#716]
Good Day IG's

Could you please review the score we have obtained in the "Fulfilling monthly requirements" section? It includes our contribution to the "developers.wax" portal as well as our participation in the quick implementation of the Hotfix, but we have received the same score as those guilds that only participated in the Hotfix application.

Furthermore, I would like to provide an update on the current situation of our Hyperion service, just for information purposes.

In mid-July, after a maintenance operation, the data cluster began to behave unusually. For this reason, we added a new node to the cluster. However, the result was not as expected, and the data balancing between the old nodes of the cluster and the new node is causing delays in indexing and queries, as reported in the evaluation report.

Since this anomalous behavior has been persistent, we have taken the following measures:

- We are creating a new Hyperion cluster (Half) with data up to 3 months old to restore minimum services as soon as possible.
- Once the new service is operational, we will completely recondition the Full service with new nodes.

Our intention is to restore the Full Hyperion service as soon as possible while keeping the Half service as a backup to prevent any future service disruptions.

Thank you

**Comment by kaefergeneral** [comment]
The score has been adjusted. 
Thanks for the heads-up.
