### ISSUE TITLE
RATING APPEAL - blacklusion

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#720]
Good Day IG's

Checking the submission, most of the points seem fair. Not entirely sure :

**illlusive.GG**: To be honest we were a bit surprised to receive the minimum score of just 1 point on this product. This puts it in the same category as some other basic tools. However, in our eyes, this is a multitude more complex to run. To keep it short: Our product requires maintaining social media channels and building a community (as we have shown in the report, we have also substantially grown since the last evaluation period +700followers), it requires research (yes we show NFTs like other pages as well, but in a more user-friendly way, targeted towards more traditional Web2 gamers. A focus that is quite important for WAX in our opinion and that requires research), we have built out a custom listing dashboard that allows games to list and maintain their games, we have an ongoing active development and a planned roadmap. In short: We understand that we won't get the maximum points right away, but this is one of the products we would love to focus on completely long-term as believe it could greatly impact the ecosystem. In this case, it is probably best to schedule a call soon, as I would love to hear more about the reasonings and input of the OIG.

Thank you

**Comment by kaefergeneral** [comment]
Dear Leonard,
after further review, we decided to increase the score of illusive.gg to a score of 2.
Please schedule a product introduction call with us and provide us with metrics for the next evaluation. 

Best,
your OIG
