### ISSUE TITLE
RATING APPEAL (guild.waxdao)

### ISSUE THREAD

**Issue by mdcryptonfts** [wax-office-of-inspector-general/waxguilds#762]
Good Day IG's

I noticed we were awarded no points for engagement, even though 4 WAX-specific videos were published on Mike D Crypto YouTube channel... these videos were not specific to WaxDAO itself, they were general WAX related content.

Not sure if this was an oversight or if the videos just didn't qualify for some other reason.

Would appreciate some clarification, thank you!

[Backed WAX Explained](https://youtu.be/cZPcG1Qpz7g)

[Table Migration Tutorial](https://youtu.be/WfydrnN_iWg)

[Claim Ownership Of Cloud Wallet](https://youtu.be/ZDHz7WP_uwI)

[Alcor Logo Tutorial](https://youtu.be/pL68Llsr9pA)

**Comment by rakeden** [comment]
Hello fellow WAX guild,

thanks for bringing this to our attention!

We looked into this issue and conclude that a score of 0.5 points for "Education Content" is justified as a good starting point.
Going forward the score could improve through consistent updates and possibe engagement on the WAX developer docs.

Looking forward to your updates!

cheers,
the OIG
