### ISSUE TITLE
RATING APPEAL - WAXMADRID 

### ISSUE THREAD

**Issue by EosioMadrid** [wax-office-of-inspector-general/waxguilds#763]
Hello IGs,

First and foremost, thank you for your review.

I would like to request a re-evaluation of the ecosystem development score.

As indicated in the last report, I have added a second URL that includes full block log and full state history backup ( https://wax-blocks-state-history.eosiomadrid.io ).  This one seems to have not been taken into consideration. The backup is done twice a month being the 27th of August the last.

This complements the original URL ( https://wax-backups.eosiomadrid.io ), which contains both mainnet and testnet snapshots and the atomicapi db backup.

I understand that this might have caused some confusion, and I hope to consolidate all resources under a single URL  for the next revision.

I am looking forward to any comment you'd like to share or any questions you may have.

Once again, thank you for your valuable work.

**Comment by rakeden** [comment]
Hello fellow WAX guild,

thanks for your appeal!
Based on the fact that you will be providing those snapshot in the future we are going to up the score to a total of 1.

cheers, 
the OIG
