### ISSUE TITLE
RATING APPEAL bp.alcor

### ISSUE THREAD

**Issue by Zzullerr** [wax-office-of-inspector-general/waxguilds#764]
Good Day IG's

We bring to your attention several pivotal developments within the Alcor Exchange ecosystem that merit careful consideration at the moment of punctuating the products. 

1. Alcor Exchange: 

Alcor Exchange, though appearing as a singular entity, comprises two distinct components and products. Spot and Automated Market Maker (AMM). We firmly contend that each of these elements should be evaluated individually, as they contribute substantial value by themselves, enough to be graded over 5 points. Our argument for this is rooted in several compelling reasons.

**Alcor Spot Trading:**

Alcor Spot trading represents the **only** spot and OTC platform on the WAX blockchain, facilitating a staggering monthly trade volume exceeding 4 million WAXP tokens with over 5k daily active users. This platform has garnered consistent support for over four years, becoming an integral part of the ecosystem.

Its services encompass Limit Trade, Depth Chart, Market Trade, Trade History (both individual and public), open order availability, and a technical analysis chart, powered by TradingView, with a comprehensive dataset spanning three years.

The impact of the Spot trading is publicly available on Top Spot Pairs https://wax.alcor.exchange/analytics/  

**Alcor Swap AMM:**

Alcor Swap AMM is the sole AMM providing concentrated liquidity on the WAX blockchain. This empowers users with the freedom to tailor their liquidity ranges and fee structures to their preferences. The impact of concentrated liquidity in the ecosystem can be witnessed through [TLM](https://wax.alcor.exchange/positions/new?left=wax-eosio.token&right=tlm-alien.worlds) (Alien Worlds) and [USDT ](https://wax.alcor.exchange/positions/new?right=usdt-usdt.alcor)charts.

To access AMM data conveniently, we've introduced the Alcorlytics website, enhancing transparency and accessibility.
These components have been consistently nurtured and fortified for over three years. Our recent introduction of Alcor Swap V2, incorporating concentrated liquidity, underscores our commitment to improving the user experience, resolving issues, and providing valuable tools like Alcorlytics. 

It is also worth mentioning that Alcor DEX provides the **lowest fees** compared to all the rest of Swaps on WAX. Alcor has a multi-route system that allows users to always receive the best deal when swapping. Moreover, Alcor covers your CPU fee if you are running low on it. 

2. TWAP and Off-chain Price Oracle: A Case for Necessity

We present TWAP and Off-chain Price Oracle as two indispensable products, each serving a distinct yet crucial role.

**[TWAP (Time-Weighted Average Price):](https://medium.com/@alcorexchange/alcor-price-oracle-securing-accurate-asset-prices-on-the-blockchain-2945e1025fea)**

While TWAP may be a recent addition, its adoption by various projects, including the WAX team, underscores its importance. The vulnerability of relying on centralized exchanges (CEXs) becomes evident when considering potential pair shutdowns, as exemplified by the recent closure of the Bittrex [WAXP-ETH pair.](https://api.bittrex.com/v3/markets/WAXP-ETH/ticker)
Alcor's commitment to simplifying TWAP usage continues, with plans to make it accessible through the WAX developer portal (already in talks with Rakeden).

**Off-chain Price Oracle:**

Our Off-chain API price oracle is the backbone of the ecosystem, processing a substantial 53.54 requests per second. It serves as a vital resource for popular APIs, including api/markets, api/v2/swapRouter/getRoute, api/v2/swap/pools, and v1/chain/get_table_rows.

Numerous projects, including notable names like Wombat, NeftyBlocks, Novopangea, WAXDao, and independent developers, depend on its reliability.

To enhance accessibility and usability, we've introduced the Alcor Discord bot, now listed on top.gg, offering an additional tool for seamless interaction for the WAX community, The bot hasn´t been promoted yet but it is already being tested in 5 WAX community Discord servers. 

3. IBC Bridge: Addressing Shortcomings and Realizing Potential

Our IBC Bridge (the only one available on WAX), evaluated at 2 points in the last assessment, has witnessed substantial improvements, fundamentally altering its landscape.

Avral, Alcor´s CEO, has been tackling issues openly on the IBC telegram such as "invalid block signatures" and "invalid block merkle proof," thereby significantly enhancing the IBC service on WAX. We would like to thank the Antelope team and EOS USA for the support provided in this process with indexing. 

Ongoing fixes, including the addition of history, reworking the interface and retry transaction buttons, have vastly improved the user experience.

Our commitment to bridging the Wombat token exemplifies our dedication to the Antelope ecosystem and WAX DeFi, enabling seamless trading across multiple chains. The IBC bridge interface and support continue to be a free service for every user.

The surge in the volume of USDT and EOS bridged to the WAX blockchain, accompanied by an increase in the number of holders, emphasizes the growing significance of these bridged tokens. Their influence on DeFi can be observed through Alcorlytics, they have become the top 5 trading pairs on WAX within a few months of launch.  and we have plans to further impact the ecosystem with yield farming in the near future.

Thank you

**Comment by rakeden** [comment]
Hello fellow WAX guild,

1. We have split both products and granted each a score of 3 points. Please keep submitting metrics and stats so that we can evaluate your products to compared ecosystem efforts.

2. We should have a product introduction call, if you want a higher score. Leaving this unchanged.

3. We can't grant more points due to the current utilisation and volume of the product. The current score incorporates your efforts and improvement over the past evaluation period. We see a great potential for this product, but not under current market conditions.


cheers,
the OIG
