### ISSUE TITLE
RATING APPEAL - guild.taco

### ISSUE THREAD

**Issue by FedeGens** [wax-office-of-inspector-general/waxguilds#766]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

`1. Ecosystem #1: NFT World Cup Bridge`
The NFT World Cup Bridge (Intraverse) has not been valued and added to the scoring table. We helped them to integrate the WAX blockchain to their cross-chain tournament system providing code examples, free infrastructure access and active support on the whole flow. This enabled WAX games and projects the opportunity to participate to the event. We'd like to add it was done completely free of charge to try to expand the WAX blockchain to other users.

We are free to provide any other info that may be useful.

Thank you.

**Comment by kaefergeneral** [comment]
Thanks for the notification.

We added a score of two as ecosystem contribution. 
Please remind us and submit metrics as it takes place again.
