### ISSUE TITLE
WAX software Releases and Tags-  Maintenance

### ISSUE THREAD

**Issue by rakeden** [wax-office-of-inspector-general/waxguilds#768]
Make sure the Tags and releases on the official WAX repository are aligned with the current hotfix situation, e.g. v3.2.3wax01: 

'Latest' version should always be tagged correctly to ease onboarding of new developers.

Also make sure that minor Tags get released. 

Bonus: Release wax4.0.4x before announcing upgrade of network through guidelines

**Comment by porkchop** [comment]
I think these are all addressed now:
https://github.com/worldwide-asset-exchange/wax-blockchain/tags
https://github.com/worldwide-asset-exchange/wax-blockchain/releases

**Comment by rakeden** [comment]
This is done and closed!
