### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by EOS-Arabia** [wax-office-of-inspector-general/waxguilds#806]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. We submitted this product: https://vstate.eosarabia.net in our report but we found a note that said we had missed the metrics and 
    bugs.
   We already fixed the bugs related to missing data and added the metrics to the submission.

![Vstat](https://github.com/wax-office-of-inspector-general/waxguilds/assets/47085785/73df3942-ee79-4be1-9f84-374d38b0657f)

Thank you, your efforts are appreciated.

**Comment by blocksbarcelona** [comment]
Hi Basel, we've reviewed and awarded points for the full history. Regarding the vstate project, we began to recognise and award points for it two years ago. However, in its current state, we don't see how it contributes to the improvement of the WAX ecosystem. We may consider awarding points in the future if we observe significant improvements in the project. It might be beneficial to arrange a call with us to discuss it further.
