### ISSUE TITLE
RATING APPEAL from Defibox BP - October

### ISSUE THREAD

**Issue by DefiboxTeam** [wax-office-of-inspector-general/waxguilds#807]
Good Day IG's

Thank you for your support all the time.

Can you please have a look at the points we have awarded for the following:

1. Price oracle - Reason for appeal: our service of bp.box price oracle machine has been running, but the price source we obtained from https://api.bittrex.com has a trading pair that was delisted and did not get the prices of EOS_USD and WAXP_ETH, causing the price feed to fail. At present, We have repaired and restored normal price feeding, and will add corresponding oracle monitoring. If we encounter this problem in the future, we will handle it in a timely manner;

2. Testnet History Solution - Reason for appeal: around August 13th, our technicians discovered that there was a problem with the server disks currently used by the WAX   nodes, and all the data was abnormal. The server manufacturer suggested that we need to replace the disks and resynchronize all the data. Therefore, the full data for several days during this period was not available. It was normal. After using it for a period of time, the server disk abnormality occurred again around August 30th, causing all data access abnormalities. The disk data needed to be replaced again and the data resynchronized. Although we urgently repaired it, it still caused full data access for several days. is abnormal

What we have done and will continue doing:
Technical updates:
1. The obtained price source https://bittrex.com has a trading pair that was delisted and did not obtain the prices of EOS_USD and WAXP_ETH, causing the price feeding to fail. The logic has been adjusted, the price feeding function of the oracle has been restored, and monitoring reminders have been added;

2. Node server maintenance processing, including data abnormality resynchronization, service abnormality recovery, etc.;

For the product and community:
We will start our Lucky BOX game 2.0 from next week, stay tuned

Unfortunately Defibox BP dropped out of Standby BP list, the above is the appeal for the latest report. Hope it can explain things well. If it won't make any changes for this month Defibox BP evaluation, we will still learn and make it better next time. 

Thank you

Kind regards
Defibox Team

**Comment by kaefergeneral** [comment]
Hello Defibox,
Unfortunately, we can not grant points for the service running if it is not pushed to the chain.
Same as you, many have been experiencing the same in August, but were able to solve the issue in a timeline manner even without proper monitoring as it was discussed widely at the time.  

We appreciate the update, but going forward, please make sure to include information like this in your update submission. Appeals should only highlight issues and obscurities with your evaluation.
We evaluate specific time periods, updates or changes that are implemented outside of the given evaluation period will not impact the rating score.

Kind regards,
your OIG
