### ISSUE TITLE
RATING APPEAL - Detroit Ledger Technologies

### ISSUE THREAD

**Issue by eosiodetroit-adam** [wax-office-of-inspector-general/waxguilds#850]
Good Day IG's

Can you please have a look at the products that were graded this reporting period?

1. We submitted the multi-chain version of Open Block Explorer as a community tool product because it includes WAX and is public at explorer.antelope.io and are actively contributing to the project in ways that benefit the WAX portion of the site. A number of of the other features were developed by DLT as well. The OIG portal was listed under the community tool and Open Block Explorer was not graded. We're not sure if this was intentional or what the reason for this was.

2. Smart Contract Migration Tool - We removed Smart Contract Migration tool from our most recent report (apologies if we needed to specifically state we no longer want it considered for points), to make room for OBE. This was still included as a graded product on our most recent report.

3. WAX Labs was decayed 0.5 points despite providing fixes requested by the Labs team and community during this reporting period.

Thank you!

**Comment by rakeden** [comment]
Hi DLT team,

1. Open Block Explorer (OBE) Evaluation: After thorough evaluation, we considered OBE in early stages in development and not directed at WAX at it's core. Features do not align with the WAX ecosystem requirements, are not working or missing entirely. To better serve the WAX community, key features such as WAX Cloud Wallet (WCW) login and basic interactions with smart contracts or at least tokens would be expected at least.

2. Smart Contract Migration Tool: We noted that this product was removed from your recent report. Given that it decayed to zero with this evaluation this did not really make a difference though unless there had been an update. Projects that are decayed to zero are usually kept in the score sheet unless for one evaluation unless there is another product with a higher score we can replace it with. The scoresheet will always include the products with the highest evaluation score, this is independent from what was submitted. So if a product is not included in the score sheet, it simply is considered for less (or in this case equal) points than the lowest scoring product.

3. WAX Labs Points Decay: We appreciate the notification here. The point decay was reverted as it was a leftover from before the release of the new front-end that was erroneously applied.

kind regards,
the WAX OIG
