### ISSUE TITLE
RATING APPEAL- ALCOR BP

### ISSUE THREAD

**Issue by AlcorGuild** [wax-office-of-inspector-general/waxguilds#851]
Good Day IG's

We would like to draw your attention to the Farms and IBC rating for Alcor. The synergic effect between Farms and IBC has been remarkable. Since their release, the Total Value Locked (TVL) on Alcor DEX has doubled, contributing significantly to the ecosystem's growth. Notably, the WAX/USDT pair has emerged as the most traded token pair on the WAX blockchain.

In the last review, Alcor Farms received one point. However, we'd like to highlight that since then, over 50 farms have been opened, accumulating a value of over 20K USD in rewards for our users. Alcor has diligently worked on implementing and showcasing the potential of Farms, exemplified by the successful integration with Thrive on Mars, adding value to their ecosystem.

https://twitter.com/thriveonmars/status/1734921340350521406

Moreover, the Alcor IBC bridge is a technology that demands continuous support and substantial effort to maintain, playing a crucial role in facilitating the Inter Blockchain Communication protocol within the Antelope ecosystem.

We kindly request a reassessment of the points awarded for Farms and IBC, taking into account the tangible contributions and positive impact these features have had on Alcor and the broader WAX ecosystem.

Thank you

**Comment by kaefergeneral** [comment]
Good Day @AlcorGuild,
After careful consideration, we decided to increase the score for farms overall as we agree with the significance for the ecosystem, even though impact and demand are still low.

The scoring of IBC will be regulated with future guidelines, and the score will remain unchanged for the time being.

Kind regards,
your OIG
