### ISSUE TITLE
RATING APPEAL 

### ISSUE THREAD

**Issue by Tanishv** [wax-office-of-inspector-general/waxguilds#924]
Good Day IG's

Guild Ledgerwise
Please review the points for 

1. DelphiAlert Bot - We built a bot for Guilds to get alerts in case they are not feeding prices to Delphi, it's currently used by 10 guilds. Please review and add. 

Thank you

**Comment by kaefergeneral** [comment]
Hello @Tanishv,

we added a score of 0.5 for the time being,

best wishes, 
your OIG
