### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by eosiodetroit-adam** [wax-office-of-inspector-general/waxguilds#926]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. WAX Labs Remake - We provided an update discussing maintenance tasks that the team is currently working through and the points for the project were listed as 0. We're also taking a more active role in community engagement / support in the WAX Labs channel.

2. Developer Doc Translations - We're wondering if we can get some clarification on if this was considered and awarded 0 points or if it was missed during the evaluations because the efforts on this aren't reflected as a contribution/product in the new section. Something that would also help us in making/proving the translations more useful/valuable would to be able to see the Google Analytic statistics for the developer docs website so we can measure marketing effectiveness.

Thank you!

**Comment by kaefergeneral** [comment]
Hello @eosiodetroit-adam,

1) We have been reporting issues and missing features with the reworked labs page for months, and we have yet to see fixes for most of them. Some date back as long as November last year. After not seeing any improvements and the WAX team reporting issues that prevented the use of WAX Labs altogether, we made the decision to remove the points for the time being and will re-evaluate the situation as matters improve.

2) Your contribution to the developer docs was not missed, but right now, the number of translations provided is still low and only on basic topics. The feedback we got from our Chinese community wasn't good either. The texts need review and editing, preferably by a native speaker, and quality control for formatting (hyperlinks, textboxes) before we can consider them for points.

best wishes,
your OIG
