### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by satohori** [wax-office-of-inspector-general/waxguilds#927]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. QoL API - Light API was added and we registered a traffic of 24.77k request in the last 7 days.
2. Engagement -  X Spaces were not taken into account ( last X spaces session:  02/29/2024 ) 

Neftyblocks,
Thank you

**Comment by kaefergeneral** [comment]
Hello @satohori,

Thank you for providing the missing metrics for your Light API endpoint. We are adding the score, which will be reflected in the update later today.

We will appoint a score of 0.5 for the Twitter spaces until further review.

Best wishes,
your OIG
