### ISSUE TITLE
RATING APPEAL - blacklusionx

### ISSUE THREAD

**Issue by leonardofficial** [wax-office-of-inspector-general/waxguilds#929]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

**Novopangea War release**
 This has been in the making for quite some time already and last we were told it will be credited once the game is live. 

>Now it is

<img width="609" alt="Screenshot 2024-03-13 at 23 24 44" src="https://github.com/wax-office-of-inspector-general/waxguilds/assets/51051978/2cbe3eae-f428-46e7-89b4-62fe67903fe9">

**What part did we play?**
We've met Novopangea through our efforts with illusive and connected him with some old business partners. Novo wanted to build a 3D version of the game but didn't exactly know where to start. We help them get a headstart. Our efforts got a studio, that hasn't been involved with WAX before involved into WAX. We pitched WAX to the studio numerous times before and this was the perfect opportunity to build something.

**What value does this provide**
The value provided through our efforts is actually twofold:
1. Novopangea launches faster and more cost-efficient, through our previous connections with the game studio. Additionally, we are actually seeing more 3D gameplay on WAX. I shouldn't need to explain in an appeal that we need actual gameplay on WAX and not just some clickers. The novopangea War launch marks exactly that - An established project on WAX using their funds to build an improved version of the game. Exactly the types of signals we should have in the chain ecosystem
2. **Onboarding a game studio into the WAX ecosystem**. We have been pitching game studios previously to build "something" on WAX. The typical issue with game studios is that they are usually familiar with ETH-based architectures but not with WAX. By involving new companies other than the "typical" companies on WAX we are improving adoption. Again exactly what we should work towards to imo

Thank you

**Comment by kaefergeneral** [comment]
Hello @leonardofficial,
It is always difficult for us to evaluate contributions for which we aren't provided with any information or level of involvement.
This is more so true when it relates to projects existing in the ecosystem for a long time that are lacking impressive metrics to begin with.

After some internal discussion, we decided to award a score of 1 for the time being and re-evaluate as things evolve.
The score is more geared toward the onboarding of said game development studio than the impact of Novopangea.

Best wishes,
your OIG
