### ISSUE TITLE
RATING APPEAL

### ISSUE THREAD

**Issue by ankh2054** [wax-office-of-inspector-general/waxguilds#973]
Good Day IG's

Can you please have a look at the points we have awarded for the following:

1. Docker Images for var. tools - Last month we got a score of 1.5 and this we got 1, wondering whether this was a mistake?
2. Security audits - I really would like the OIG to re-consider the importance of the security audits we do on Guilds. A lot of time is spend auditing guilds and we have found a lot of vulnerabilities during this process.  Since the reports are private it's hard to share the information, but you can perhaps speak to some of the guilds we have audited for feedback.

Thank you

**Comment by kaefergeneral** [comment]
Hello @ankh2054,
1.)  The scores for your docker images have been adjusted in the process of housekeeping. The provided docker images, aside of the the delphi oracle 6 months ago, did not have any recent updates. With the weight of ecosystem contributions being increased from 9 to now 11 points and will be increased to 12 points with 5.8, the base points have been adjusted accordingly.

2.) For about the past year we have been granting points on a 'per audit' basis, granting you 0.5 points per audit completed during the timeframe. Applying a decay if you audited less than in the previous evaluation timeframe. 

Thank you for understanding and keep up the good work.
